#!/usr/bin/env python3
# ============================================================================
#  CCDarkSens — plot_ne_signal_spectrum_compare
#  Figure 2: S(n_e) signal spectra (ionization + detector) vs n_e for
#            band-gap pheno scenarios, with dark-current background overlay
#
#  Author: Diego Venegas-Vargas
# ============================================================================
"""
Compare the electron-number (n_e) signal spectrum across band-gap pheno
scenarios at a single DM point, in n_e space, reading existing framework
ROOT outputs (no physics is recomputed here).

  python3 utils/plot_ne_signal_spectrum_compare.py
  python3 utils/plot_ne_signal_spectrum_compare.py --dc-tier dc10x
  python3 utils/plot_ne_signal_spectrum_compare.py --dc-tier dc100x --klein-gaps 0.1,0.5

Inputs (generated by configs/ne_imaging_one_point_*_dc10x.json etc.):
  outputs/band_gap_ne_imaging/si_ref_dc10x/scan_dmelectron_pattern.root
  outputs/band_gap_ne_imaging_klein/klein_gap0p1_dc10x/scan_dmelectron_pattern.root

Output: outplots/band_gap_pheno/ne_imaging/ne_signal_spectrum_compare[_dc10x].pdf
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

import uproot  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "utils"))
from band_gap_klein_plot import (  # noqa: E402
    COLOR_SI_REF,
    DEFAULT_KLEIN_GAPS,
    filter_klein_gaps,
    gap_scan_id,
    klein_eh,
    klein_mathtext_label,
    parse_float_list,
)

OUTBASE_KLEIN = ROOT / "outputs" / "band_gap_ne_imaging_klein"
OUTBASE_ORIG = ROOT / "outputs" / "band_gap_ne_imaging"

# Fixed hue per E_gap — categorical, not a sequential gradient.
FIG2_GAP_COLORS = {
    0.1: "#E41A1C",  # red
    0.3: "#377EB8",  # blue
    0.5: "#4DAF4A",  # green
    0.7: "#984EA3",  # purple
    0.9: "#FF7F00",  # orange
    1.2: "#A65628",  # brown (unused when Si ref is shown)
}
FIG2_GAP_COLOR_FALLBACK = "#17BECF"  # cyan if an unlisted gap is requested

NE_BINS = [1, 2, 3, 4, 5]

MCHI_MEV = 1.007781
SIGMA_E_CM2 = 1.1e-35
EXPOSURE = "0.5 kg·yr"

MEDIATORS = [
    ("heavy", r"Heavy mediator ($F_{DM}=1$)"),
    ("light", r"Light mediator ($F_{DM}\propto 1/q^2$)"),
]

LOG_FLOOR = 1e-3

DC_LAMBDA = {
    "baseline": 0.0365,
    "dc10x": 0.365,
    "dc100x": 3.65,
}


def fig2_gap_color(gap_ev: float) -> str:
    for key, color in FIG2_GAP_COLORS.items():
        if abs(gap_ev - key) < 1e-6:
            return color
    return FIG2_GAP_COLOR_FALLBACK


def dc_rate_text(lam_e_per_pix_per_year: float) -> str:
    """Dark-current rate label in e⁻/pix/year."""
    return rf"DC $= {lam_e_per_pix_per_year:g}\ \mathrm{{e}}^-\!/\mathrm{{pix}}/\mathrm{{yr}}$"


def scen_dir_id(scen_id: str, dc_tier: str) -> str:
    if dc_tier == "baseline":
        return scen_id
    return f"{scen_id}_{dc_tier}"


def default_out_path(dc_tier: str) -> Path:
    stem = "ne_signal_spectrum_compare"
    if dc_tier != "baseline":
        stem += f"_{dc_tier}"
    return ROOT / "outplots" / "band_gap_pheno" / "ne_imaging" / f"{stem}.pdf"


def build_scenarios(klein_gaps, include_si_ref: bool, dc_tier: str):
    scenarios = []
    if include_si_ref:
        scenarios.append(
            (
                scen_dir_id("si_ref", dc_tier),
                OUTBASE_ORIG,
                r"Si ref  $(1.2,\ 3.8)$",
                COLOR_SI_REF,
            )
        )
    for g in klein_gaps:
        eh = klein_eh(g)
        sid = scen_dir_id(gap_scan_id(g), dc_tier)
        scenarios.append(
            (
                sid,
                OUTBASE_KLEIN,
                klein_mathtext_label(g, eh),
                fig2_gap_color(g),
            )
        )
    return scenarios


def _values_by_ne(hist, ne_list=NE_BINS) -> np.ndarray:
    centers = hist.axis().centers()
    vals = hist.values()
    out = []
    for ne in ne_list:
        i = int(np.argmin(np.abs(centers - ne)))
        out.append(float(vals[i]))
    return np.array(out)


def _first_key(f, prefix: str) -> str | None:
    for k in f.keys():
        kk = k.split(";")[0]
        if kk.startswith(prefix):
            return kk
    return None


def load_scenario(scen_id: str, outbase: Path) -> dict:
    scan_path = outbase / scen_id / "scan_dmelectron_pattern.root"
    out = {"S_true": None, "S_obs": None, "B_tot": None}
    if scan_path.is_file():
        with uproot.open(scan_path) as f:
            st_key = _first_key(f, "S_true_ne__")
            so_key = _first_key(f, "S_obs_ne__")
            if st_key:
                out["S_true"] = _values_by_ne(f[st_key])
            if so_key:
                out["S_obs"] = _values_by_ne(f[so_key])
            if "B_tot_ne" in [k.split(";")[0] for k in f.keys()]:
                out["B_tot"] = _values_by_ne(f["B_tot_ne"])
    else:
        print(f"  WARN: missing {scan_path}")
    return out


def _draw_grouped_bars(ax, data_by_scen: list, key: str, scenarios) -> None:
    x = np.arange(len(NE_BINS))
    n = len(scenarios)
    width = 0.8 / n
    for j, (_, _, label, color) in enumerate(scenarios):
        vals = data_by_scen[j][key]
        if vals is None:
            continue
        plotted = np.where(vals > LOG_FLOOR, vals, np.nan)
        offs = x + (j - (n - 1) / 2.0) * width
        ax.bar(
            offs,
            plotted,
            width=width,
            color=color,
            edgecolor="black",
            linewidth=0.4,
            label=label,
            zorder=3,
        )


def _draw_background(ax, b_tot: np.ndarray, dc_label: str) -> None:
    x = np.arange(len(NE_BINS))
    for i in range(len(NE_BINS)):
        b = b_tot[i]
        if b <= 0:
            continue
        ax.hlines(
            b,
            x[i] - 0.45,
            x[i] + 0.45,
            colors="0.25",
            linestyles="--",
            lw=1.6,
            zorder=4,
            label=rf"$B_{{\mathrm{{tot}}}}(n_e)$ ({dc_label} + flat)" if i == 0 else None,
        )


def _draw_mediator_panel(
    axes_row, data_by_scen: list, mediator_label: str, scenarios, dc_label: str
) -> None:
    axL, axR = axes_row
    b_ref = next((d["B_tot"] for d in data_by_scen if d["B_tot"] is not None), None)
    _draw_grouped_bars(axL, data_by_scen, "S_true", scenarios)
    _draw_grouped_bars(axR, data_by_scen, "S_obs", scenarios)
    if b_ref is not None:
        _draw_background(axL, b_ref, dc_label)
        _draw_background(axR, b_ref, dc_label)
    for ax, title in (
        (axL, r"$S_{\mathrm{true}}(n_e)$ — ionization (FoldToNe)"),
        (axR, r"$S_{\mathrm{obs}}(n_e)=S_{\mathrm{true}}\cdot\varepsilon(n_e)$"),
    ):
        ax.set_yscale("log")
        ax.set_xticks(np.arange(len(NE_BINS)))
        ax.set_xticklabels([str(ne) for ne in NE_BINS])
        ax.set_xlabel(r"$n_e$ [electrons]")
        ax.set_title(title, fontsize=9)
        ax.grid(True, which="both", axis="y", ls=":", alpha=0.3)
        ax.legend(loc="upper right", fontsize=7.5, framealpha=0.92)
    axL.set_ylabel(mediator_label + "\nExpected counts")


def outbase_for(base: Path, med_key: str) -> Path:
    if base == OUTBASE_KLEIN and med_key == "light":
        return ROOT / "outputs" / "band_gap_ne_imaging_klein_light"
    if base == OUTBASE_ORIG and med_key == "light":
        return ROOT / "outputs" / "band_gap_ne_imaging_light"
    return base


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--out", type=Path, default=None)
    ap.add_argument(
        "--dc-tier",
        choices=["baseline", "dc10x", "dc100x"],
        default="baseline",
        help="Dark-current tier for output subdirs (default: baseline)",
    )
    ap.add_argument(
        "--klein-gaps",
        type=str,
        default=",".join(str(g) for g in DEFAULT_KLEIN_GAPS),
        metavar="CSV",
        help="Comma-separated E_gap [eV] for Klein bars "
        f"(default: {','.join(str(g) for g in DEFAULT_KLEIN_GAPS)}). "
        "Missing ROOT scans are skipped with a warning.",
    )
    ap.add_argument(
        "--no-si-ref",
        action="store_true",
        help="Omit the Si reference scenario from the comparison.",
    )
    args = ap.parse_args()
    out_path = args.out if args.out is not None else default_out_path(args.dc_tier)

    klein_gaps = filter_klein_gaps(parse_float_list(args.klein_gaps))
    scenarios = build_scenarios(
        klein_gaps, include_si_ref=not args.no_si_ref, dc_tier=args.dc_tier
    )
    if not scenarios:
        print("ERROR: no scenarios to plot", file=sys.stderr)
        return 1

    lam = DC_LAMBDA[args.dc_tier]
    dc_label = dc_rate_text(lam)

    fig, axes = plt.subplots(
        len(MEDIATORS), 2, figsize=(13.0, 5.6 * len(MEDIATORS)), sharey="row"
    )

    for row_idx, (med_key, med_label) in enumerate(MEDIATORS):
        data = [
            load_scenario(sid, outbase_for(ob, med_key)) for sid, ob, _, _ in scenarios
        ]
        _draw_mediator_panel(axes[row_idx], data, med_label, scenarios, dc_label)

    fig.suptitle(
        r"$n_e$-space signal spectrum — Klein $\varepsilon_h=2.8\,E_g+0.5$ — "
        rf"$m_\chi={MCHI_MEV:.2f}$ MeV, $\bar\sigma_e={SIGMA_E_CM2:.1e}$ cm$^2$, {EXPOSURE}"
        + "\n"
        + dc_label,
        fontsize=12,
    )
    msg = (
        r"Klein formula: lower-gap material populates higher $n_e$ bins "
        r"$\rightarrow$ discrimination against $n_e{=}1$ dark current "
        rf"({dc_label})."
    )
    fig.text(0.5, 0.005, msg, ha="center", va="bottom", fontsize=9, style="italic")
    fig.tight_layout(rect=(0, 0.03, 1, 0.96))

    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path)
    fig.savefig(out_path.with_suffix(".png"), dpi=150)
    plt.close(fig)

    print(f"DC: {lam:g} e-/pix/yr ({args.dc_tier})")
    print(f"Scenarios: {[s[0] for s in scenarios]}")
    print(f"Reference: m_chi={MCHI_MEV} MeV, sigma_e={SIGMA_E_CM2} cm^2")
    print(f"Wrote {out_path}")
    print(f"Wrote {out_path.with_suffix('.png')}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
