// ============================================================================
//  CCDarkSens — ccdarksens_scan_dmelectron_pattern
//
//  Full DM–electron sensitivity scan over a (mχ, σ_e) grid.
//
//  Pipeline summary
//  ─────────────────
//  1. Load pre-computed dR/dE(mχ, σ_e) rate tables from per-mass CSV files
//     (generated by QEDark / ccdarkphys).
//  2. Fold dR/dE through ChargeIonization → S_true(n_e) expected counts.
//  3. Fold S_true through ε(pattern | n_e) to obtain S_pat per ROI bin.
//  4. Build background B_pat from dark-current + flat d.r.u. migration,
//     or from a pre-computed Bp / Br template.
//  5. For each (mχ, σ_e) grid point compute the profile likelihood ratio:
//       q_μ = 2 · [NLL(S+B, θ̂_μ) − NLL(B, θ̂)]
//     where θ scales the Br background shape nuisance parameter.
//  6. Extract the 90 % CL upper limit by finding where q_μ = Z_α²
//     (default α = 0.90).
//  7. Write the per-mass UL graph and the q(mχ,σ) histogram to a ROOT file.
//
//  Observable spaces   (JSON: experiment.observable_bins)
//  ────────────────────────────────────────────────────────
//  • "pattern"  – six SRDM pattern bins {11, 21, 111, 31, 22, 211}
//  • "ne"       – n_e multiplicity bins {1 … 5} with flat ε(n_e)
//
//  Minimiser options   (JSON: run.profile_minimizer)
//  ───────────────────────────────────────────────────
//  • "brent"    – 1-D Brent over θ per σ point (fast default)
//  • "minuit"   – 1-D Minuit over θ; cross-checks Brent result
//  • "minuit2d" – 2-D Minuit over (log₁₀ σ_e, θ) once per mχ
//  • "pydme"    – 2-D Minuit + bisection bracket (closest to pydme output)
//
//  Usage
//  ──────
//    ccdarksens_scan_dmelectron_pattern <config.json>
//  Output: <run.outdir>/scan_dmelectron_pattern.root
//
//  Author: Diego Venegas-Vargas
// ============================================================================

#include <algorithm>
#include <chrono>
#include <cmath>
#include <limits>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <memory>
#include <string>
#include <vector>
#include <sstream>
#include <map>
#include <set>
#include <cctype>

#include <TH1D.h>
#include <TH2D.h>
#include <TFile.h>
#include <TParameter.h>
#include <TMath.h>
#include <TCanvas.h>
#include <TGraph.h>
#include <TLine.h>
#include <TLatex.h>

#include <nlohmann/json.hpp>

#include "ccdarksens/io/ConfigManager.hh"
#include "ccdarksens/model/DMElectronModel.hh"
#include "ccdarksens/experiment/ExperimentSetup.hh"

#include "ccdarksens/response/ChargeIonization.hh"
#include "ccdarksens/response/Diffusion.hh"
#include "ccdarksens/response/ChargeTransport.hh"
#include "ccdarksens/response/PixelSimulator.hh"
#include "ccdarksens/response/PatternClassifier.hh"
#include "ccdarksens/response/EfficiencyMC.hh"
#include "ccdarksens/response/PatternImageGenerator.hh"
#include "ccdarksens/response/PatternRates.hh"
#include "ccdarksens/response/DetectorResponsePipeline.hh"
#include "ccdarksens/response/PCDBasedResponse.hh"
#include "ccdarksens/response/PCDCalculator.hh"
#include "ccdarksens/stats/TestStatisticFactory.hh"
#include "ccdarksens/stats/ProfileLikelihood.hh"
#include "ccdarksens/stats/PoissonAsimovPLR.hh"

#include "ccdarksens/backgrounds/BackgroundBuilder.hh"

using nlohmann::json;
using namespace ccdarksens;

#include "ccdarksens/utils/AppUtils.hh"
static auto expand_axis = [](const json& spec, const std::string& kind) {
  return ccdarksens::utils::ExpandAxis(spec, kind);
};

static const json* EfficiencyMcJsonBlock(const json& jroot) {
  if (!jroot.contains("response")) return nullptr;
  const auto& jresp = jroot["response"];
  if (jresp.contains("efficiency_mc")) return &jresp["efficiency_mc"];
  if (jresp.contains("pattern_mc")) return &jresp["pattern_mc"];
  return nullptr;
}

static std::vector<double> ObservedCountsFromConfig(
    const json& jroot, const std::vector<int>& roi_ids) {
  if (!jroot.contains("run")) return {};
  const auto& jr = jroot["run"];
  if (!jr.contains("observed_counts") || jr["observed_counts"].is_null())
    return {};
  auto counts = jr["observed_counts"].get<std::vector<double>>();
  if (counts.empty()) return {};
  if (counts.size() != roi_ids.size()) {
    throw std::runtime_error(
        "run.observed_counts size (" + std::to_string(counts.size()) +
        ") must match pattern_roi/roi_bins size (" +
        std::to_string(roi_ids.size()) + ")");
  }
  return counts;
}

static std::string format_sigma(double sigma, const std::string& fmt)
{
  int prec = 6;
  if (!fmt.empty() && fmt.front() == '.' &&
      (fmt.back() == 'e' || fmt.back() == 'E')) {
    try {
      prec = std::stoi(fmt.substr(1, fmt.size() - 2));
    } catch (...) {
      prec = 6;
    }
  }
  std::ostringstream ss;
  ss.setf(std::ios::scientific);
  ss << std::setprecision(prec) << sigma;
  return ss.str();
}

static std::string format_double(double x, const std::string& fmt)
{
  int prec = 6;
  if (!fmt.empty() && fmt.front() == '.') {
    try {
      // Accept ".6" or ".6f"
      std::string digits = fmt.substr(1);
      if (!digits.empty() && (digits.back() == 'f' || digits.back() == 'F'))
        digits.pop_back();
      prec = std::stoi(digits);
    } catch (...) {
      prec = 6;
    }
  }
  std::ostringstream ss;
  ss.setf(std::ios::fixed);
  ss << std::setprecision(prec) << x;
  return ss.str();
}

/// UL from monotonized q(σ) on the scan grid — same crossing logic as ccdarksens_plot_dmelectron_limit (--from-qhist).
static double UlFromQMonoCrossing(const std::vector<double>& sigma_list,
                                  const std::vector<double>& q_mono,
                                  double target_q)
{
  if (sigma_list.empty() || q_mono.size() != sigma_list.size())
    return sigma_list.empty() ? 0.0 : sigma_list.back();
  const size_t Ny = sigma_list.size();
  for (size_t k = 0; k + 1 < Ny; ++k) {
    const double q1 = q_mono[k];
    const double q2 = q_mono[k + 1];
    if (q1 < target_q && q2 >= target_q && q2 > q1) {
      const double s1 = sigma_list[k];
      const double s2 = sigma_list[k + 1];
      if (s1 <= 0.0 || s2 <= 0.0) break;
      const double logS1 = std::log10(s1);
      const double logS2 = std::log10(s2);
      const double t = (target_q - q1) / (q2 - q1);
      return std::pow(10.0, logS1 + t * (logS2 - logS1));
    }
  }
  const double q_min = *std::min_element(q_mono.begin(), q_mono.end());
  if (q_min >= target_q)
    return sigma_list.front();
  const int k_best = static_cast<int>(
      std::min_element(q_mono.begin(), q_mono.end()) - q_mono.begin());
  for (int k = k_best; k < static_cast<int>(Ny); ++k) {
    if (q_mono[static_cast<size_t>(k)] >= target_q)
      return sigma_list[static_cast<size_t>(k)];
  }
  return sigma_list.back();
}

/// Load observed counts from CSV (one row comma-separated or one per line). Returns empty on error.
static std::vector<double> load_data_csv(const std::string& path, std::size_t expected_size)
{
  std::ifstream in(path);
  if (!in) return {};
  std::vector<double> out;
  std::string line;
  while (std::getline(in, line)) {
    std::istringstream ss(line);
    std::string cell;
    while (std::getline(ss, cell, ',')) {
      try {
        out.push_back(std::stod(cell));
      } catch (...) { break; }
    }
    if (out.size() >= expected_size) break;
  }
  return out;
}

/// Parse histogram bin label (pattern code or n_e) to integer; -1 on failure.
static int parse_data_bin_label(const char* label)
{
  if (!label || !label[0]) return -1;
  try {
    return std::stoi(label);
  } catch (...) {
    return -1;
  }
}

/// Load observed counts from ROOT file (histogram D_pat).
/// When roi_ids is set and the histogram has axis labels, map each ROI id to its bin
/// content (0 if missing). Otherwise fall back to sequential bin order (legacy).
static std::vector<double> load_data_root(const std::string& path,
                                          std::size_t expected_size,
                                          const std::vector<int>* roi_ids = nullptr)
{
  (void)expected_size;
  TFile f(path.c_str(), "READ");
  if (!f.IsOpen()) return {};
  TH1D* h = nullptr;
  f.GetObject("D_pat", h);
  if (!h) return {};
  const int nb = h->GetNbinsX();

  std::map<int, double> by_id;
  bool has_labels = false;
  for (int i = 1; i <= nb; ++i) {
    const char* lbl = h->GetXaxis()->GetBinLabel(i);
    const int id = parse_data_bin_label(lbl);
    if (id >= 0) {
      has_labels = true;
      by_id[id] = h->GetBinContent(i);
    }
  }

  if (roi_ids && !roi_ids->empty() && has_labels) {
    std::vector<double> out;
    out.reserve(roi_ids->size());
    for (int pid : *roi_ids) {
      auto it = by_id.find(pid);
      out.push_back(it != by_id.end() ? it->second : 0.0);
    }
    return out;
  }

  std::vector<double> out;
  out.reserve(static_cast<std::size_t>(nb));
  for (int i = 1; i <= nb; ++i) out.push_back(h->GetBinContent(i));
  return out;
}

/// If path is .root and file contains exposure_kg_year (TParameter), set *out and return true.
static bool get_exposure_from_data_file(const std::string& path, double* out)
{
  if (!out || path.size() < 6 || path.compare(path.size() - 5, 5, ".root") != 0) return false;
  TFile f(path.c_str(), "READ");
  if (!f.IsOpen()) return false;
  TParameter<double>* p = nullptr;
  f.GetObject("exposure_kg_year", p);
  if (!p) return false;
  *out = p->GetVal();
  return true;
}

/// Load data from CSV or ROOT (D_pat). ROOT: map by bin label to roi_ids when provided.
static std::vector<double> load_data(const std::string& path,
                                     std::size_t expected_size,
                                     const std::vector<int>* roi_ids = nullptr)
{
  if (path.size() >= 5 && path.compare(path.size() - 5, 5, ".root") != 0)
    return load_data_csv(path, expected_size);
  return load_data_root(path, expected_size, roi_ids);
}

static std::vector<double> make_edges_from_centers(const std::vector<double>& c)
{
  const std::size_t N = c.size();
  std::vector<double> edges(N + 1);
  if (N == 0) return edges;

  if (N == 1) {
    const double w = std::abs(c[0]) > 0 ? std::abs(c[0]) * 0.5 : 0.5;
    edges[0] = c[0] - w;
    edges[1] = c[0] + w;
    return edges;
  }

  edges[0] = c[0] - 0.5 * (c[1] - c[0]);
  for (std::size_t i = 1; i < N; ++i) {
    edges[i] = 0.5 * (c[i - 1] + c[i]);
  }
  edges[N] = c[N - 1] + 0.5 * (c[N - 1] - c[N - 2]);
  return edges;
}

// -----------------------------------------------------------------------------
// Main
// -----------------------------------------------------------------------------
int main(int argc, char** argv)
{
  if (argc < 2) {
    std::cerr << "Usage: " << argv[0] << " config.json\n";
    return 1;
  }

  const std::string config_path = argv[1];

  try {
    // =========================================================================
    // 1. Parse JSON configuration and initialise experiment summary
    //    ConfigManager deserialises every section (detector, experiment,
    //    response, backgrounds, model, run). ExperimentSetup derives
    //    exposure_kg_year, ROI binning, and the observable-space choice.
    // =========================================================================
    ConfigManager cfg(config_path);
    cfg.parse();

    json jroot;
    {
      std::ifstream jf(config_path);
      if (!jf) {
        throw std::runtime_error("Cannot open config file " + config_path);
      }
      jf >> jroot;
    }

    const auto& run = cfg.run();
    const auto& det = cfg.detector();

    if (!run.outdir.empty()) {
      std::filesystem::create_directories(run.outdir);
    }

    // =========================================================================
    // 2. Experiment setup
    //    Derives exposure_kg_year = livetime_days × duty_cycle × mass_kg / 365.25,
    //    the n_e ROI binning, and the observable-space flag (pattern vs ne).
    // =========================================================================
    ExperimentSetup setup(cfg.experiment_cfg(), det.mass_kg(), run.rng_seed);
    auto summary = setup.prepare_summary();

    const int ne_min = summary.binning.ne_min;
    const int ne_max = summary.binning.ne_max;
    const bool use_pattern_bins = (summary.observable_bins == "pattern");
    // For background we include n_e=0 when in pattern space (dark current has n_e=0)
    const int ne_min_bkg = use_pattern_bins ? std::min(ne_min, 0) : ne_min;

    std::cout << "[scan-pattern] Exposure = " << summary.exposure_kg_year
              << " kg·year, n_e range [" << ne_min << "," << ne_max << "]\n";
    if (run.verbosity >= 1)
      std::cout << "[scan-pattern] Signal units: dR/dE from rate tables in events/(kg·year·eV); "
                << "counts = FoldToNe(dRdE, exposure_kg_year) = dR/dE * exposure_kg_year * dE; "
                << "S_pat = FoldNeToPatternRates(S_ne counts).\n";

    // =========================================================================
    // 3. Detector response components
    //    ChargeIonization converts deposited energy E_eV → n_e electron–hole
    //    pairs. ChargeTransport models lateral diffusion σ_xy(z,E) during
    //    drift. Both feed into EfficiencyMC which runs the pixel-level MC
    //    to build the ε(pattern | n_e) acceptance table.
    // =========================================================================
    const auto& ion_cfg = cfg.response().charge_ionization;
    auto ion = std::make_shared<ChargeIonization>(ion_cfg.table_csv);
    if (run.verbosity >= 1) {
      std::cout << "[scan-pattern] ChargeIonization table: " << ion_cfg.table_csv
                << " (pheno gap=" << ion_cfg.band_gap_eV << " eV, eh="
                << ion_cfg.eh_pair_eV << " eV";
      if (!ion_cfg.scenario.empty())
        std::cout << ", scenario=" << ion_cfg.scenario;
      std::cout << ")\n";
    }

    // Dark current per exposure
    const double lambda_per_year = cfg.backgrounds().lambda_e_per_pix_per_year;
    const double year_s = 365.25 * 86400.0;
    const double exp_time_s = cfg.timing().exposure_time_s;
    const double lambda_per_exp =
        (exp_time_s > 0.0 && year_s > 0.0)
            ? lambda_per_year * (exp_time_s / year_s)
            : 0.0;

    const auto& emj = cfg.response().emc;

    ChargeTransportConfig ct_cfg;
    ct_cfg.thickness_um   = det.geometry().thickness_mm * 1000.0;
    ct_cfg.A_um2          = emj.A_um2;
    ct_cfg.b_umInv        = emj.b_umInv;
    ct_cfg.alpha          = emj.alpha;
    ct_cfg.beta_per_keV   = emj.beta_per_keV;
    ct_cfg.rng_seed       = emj.rng_seed;

    auto ct = std::make_shared<ChargeTransport>(ct_cfg);

    // ---------------- EfficiencyMC (row-based) ----------------
    EfficiencyMCConfig emc_cfg;
    emc_cfg.ne_trials = emj.n_events_per_ne;
    emc_cfg.row_length = emj.row_length;

    emc_cfg.pix_cfg.mode           = PixelSimMode::RowSegment;
    emc_cfg.pix_cfg.nx             = emc_cfg.row_length;
    emc_cfg.pix_cfg.ny             = 1;
    emc_cfg.pix_cfg.pixel_size_um  = det.geometry().pixel_size_um;
    emc_cfg.pix_cfg.lambda_dc = 0.0;
    emc_cfg.pix_cfg.sigma_readout_e= emj.sigma_readout_e;
    emc_cfg.pix_cfg.rng_seed       = emj.rng_seed;
    emc_cfg.seed                   = emj.rng_seed;

    // Accepted pattern labels derived from experiment.pattern_roi
    emc_cfg.accepted_labels.clear();
    for (int code : summary.pattern_roi) {
      PatternLabel lab;
      lab.isolated = true;
      lab.q = ccdarksens::DecodePatternCode(code);
      if (!lab.q.empty()) emc_cfg.accepted_labels.push_back(lab);
    }
    if (emc_cfg.accepted_labels.empty()) {
      PatternLabel lab;
      lab.isolated = true;
      lab.q = {1};
      emc_cfg.accepted_labels.push_back(lab);
    }

    std::cout << "[scan-pattern] Accepted pattern labels (from pattern_roi):\n";
    for (std::size_t i = 0; i < emc_cfg.accepted_labels.size(); ++i) {
      std::cout << "  " << i << ": q = { ";
      for (int qv : emc_cfg.accepted_labels[i].q) std::cout << qv << " ";
      std::cout << "}  isolated = "
                << (emc_cfg.accepted_labels[i].isolated ? "true" : "false")
                << "\n";
    }


    // =========================================================================
    // 4. Pattern efficiency map
    //    Optionally loads a (pattern_code, n_e) → ε table from a CSV file
    //    specified in response.efficiency_mc.efficiency_csv. When present,
    //    PrecomputeEpsilonWithPatternEff folds it into the ε(n_e) histogram.
    //    A reference CSV (efficiency_csv_reference) can overlay extra entries.
    // =========================================================================
    std::map<std::pair<int,int>, double> pattern_eff_map;

    if (const json* j_emc = EfficiencyMcJsonBlock(jroot);
        j_emc && j_emc->contains("efficiency_csv")) {

      std::string eff_csv_path = (*j_emc)["efficiency_csv"].get<std::string>();

      if (!eff_csv_path.empty()) {
      // Resolve path relative to config file so "data/..." works from any CWD
      std::filesystem::path path_to_open(eff_csv_path);
      if (!path_to_open.is_absolute()) {
        std::filesystem::path config_dir =
            std::filesystem::absolute(std::filesystem::path(config_path)).parent_path();
        path_to_open = (config_dir / ".." / eff_csv_path).lexically_normal();
      }
      std::string eff_csv_resolved = path_to_open.string();
      if (eff_csv_resolved.empty()) {
        std::cout << "[scan-pattern] efficiency_csv is empty; will use EfficiencyMC-generated efficiencies.\n";
      } else {
      std::ifstream eff_in(eff_csv_resolved);
      if (!eff_in.is_open()) {
        throw std::runtime_error("Failed to open pattern efficiency CSV: " + eff_csv_resolved
                                + " (from config: " + eff_csv_path + ")");
      }

      std::string eff_line;
      // Parse CSV: each row is "pattern_code, n_e, efficiency"
      // Skip comment (#) and header (starts with "pattern") rows.
      while (std::getline(eff_in, eff_line)) {
        // Trim leading whitespace
        while (!eff_line.empty() && std::isspace(static_cast<unsigned char>(eff_line.front())))
          eff_line.erase(eff_line.begin());
        if (eff_line.empty() || eff_line[0] == '#') continue;
        if (eff_line.rfind("pattern", 0) == 0) continue;  // header row

        std::stringstream eff_ss(eff_line);
        std::string col;
        int pattern_code = 0, ne_val = 0;
        double eff_val = 0.0;

        if (!std::getline(eff_ss, col, ',')) continue;
        try { pattern_code = std::stoi(col); } catch (...) { continue; }

        if (!std::getline(eff_ss, col, ',')) continue;
        try { ne_val = std::stoi(col); } catch (...) { continue; }

        if (!std::getline(eff_ss, col, ',')) continue;
        try { eff_val = std::stod(col); } catch (...) { continue; }

        pattern_eff_map[{pattern_code, ne_val}] = eff_val;
      }

      if (pattern_eff_map.empty()) {
        throw std::runtime_error("Pattern efficiency CSV appears to have no valid data: "
                                + eff_csv_resolved);
      }

      std::cout << "[scan-pattern] Loaded "
                << pattern_eff_map.size()
                << " (pattern, ne) entries from " << eff_csv_resolved << "\n";

      // Optional: overlay with reference efficiencies (e.g. pydme) to fix MC mismatch
      if (const json* j_emc_ref = EfficiencyMcJsonBlock(jroot);
          j_emc_ref && j_emc_ref->contains("efficiency_csv_reference")) {
        std::string ref_path =
            (*j_emc_ref)["efficiency_csv_reference"].get<std::string>();
        if (!ref_path.empty()) {
          std::filesystem::path ref_to_open(ref_path);
          if (!ref_to_open.is_absolute()) {
            std::filesystem::path config_dir =
                std::filesystem::absolute(std::filesystem::path(config_path)).parent_path();
            ref_to_open = (config_dir / ".." / ref_path).lexically_normal();
          }
          std::ifstream ref_in(ref_to_open.string());
          if (!ref_in.is_open())
            throw std::runtime_error("Failed to open efficiency_csv_reference: " + ref_to_open.string());
          std::string ref_line;
          std::size_t n_ref = 0;
          while (std::getline(ref_in, ref_line)) {
            while (!ref_line.empty() && std::isspace(static_cast<unsigned char>(ref_line.front())))
              ref_line.erase(ref_line.begin());
            if (ref_line.empty() || ref_line[0] == '#' || ref_line.rfind("pattern", 0) == 0) continue;
            std::stringstream rss(ref_line);
            std::string rc;
            int rp = 0, rn = 0;
            double re = 0.0;
            if (!std::getline(rss, rc, ',')) continue;
            try { rp = std::stoi(rc); } catch (...) { continue; }
            if (!std::getline(rss, rc, ',')) continue;
            try { rn = std::stoi(rc); } catch (...) { continue; }
            if (!std::getline(rss, rc, ',')) continue;
            try { re = std::stod(rc); } catch (...) { continue; }
            pattern_eff_map[{rp, rn}] = re;
            ++n_ref;
          }
          std::cout << "[scan-pattern] Overlaid " << n_ref
                    << " (pattern,ne) from reference " << ref_to_open.string() << "\n";
        }
      }
      }  // else (eff_csv_resolved non-empty: we opened and loaded)
      }  // if (!eff_csv_path.empty())
    }
    if (pattern_eff_map.empty()) {
      std::cout << "[scan-pattern] No efficiency_mc.efficiency_csv (or empty); "
                   "will use EfficiencyMC-generated efficiencies.\n";
    }

    // =========================================================================
    // 5. PatternClassifier and EfficiencyMC construction
    //    PatternClassifier applies the hardware thresholds (thr_M, thr_MN,
    //    thr_MNL) and pattern labelling rules. EfficiencyMC runs N_trials
    //    pixel-level MC events per n_e value to compute ε(pattern | n_e).
    // =========================================================================
    // PatternClassifier
    PatternClassifierConfig pcc;
    const auto& pcc_temp = cfg.response().pattern_classifier;
    pcc.Qmin_e        = pcc_temp.Qmin_e;
    pcc.neighbor_Qmax_e = pcc_temp.neighbor_Qmax_e;
    pcc.Qmax_e        = pcc_temp.Qmax_e;
    pcc.enable_MN     = pcc_temp.enable_MN;
    pcc.enable_MNL    = pcc_temp.enable_MNL;
    pcc.sigma_res_e   = pcc_temp.sigma_res_e;
    pcc.max_e_per_pixel = pcc_temp.max_e_per_pixel;
    pcc.thr_M         = pcc_temp.thr_M;
    pcc.thr_MN        = pcc_temp.thr_MN;
    pcc.thr_MNL       = pcc_temp.thr_MNL;
    pcc.allow_pattern_zero = pcc_temp.allow_pattern_zero;
    pcc.single_pixel_use_round = pcc_temp.single_pixel_use_round;

    auto classifier = std::make_shared<PatternClassifier>(pcc);

    // Build EfficiencyMC as a shared_ptr so we can give it to the pipeline
    auto emc_ptr = std::make_shared<EfficiencyMC>(emc_cfg, ct, classifier);

    // Optional: build pattern efficiency from 2D image + isolation (notebook-style)
    if (emj.use_2d_image_efficiency) {
      const auto& pimg = cfg.response().pattern_image;
      const bool from_json = (pimg.nrows_binned > 0 && pimg.ncols > 0 && pimg.row_binning > 0);
      const bool from_detector = !from_json && (det.geometry().rows > 0 && det.geometry().cols > 0 && pimg.row_binning > 0 && pimg.col_binning > 0);
      if (from_json || from_detector) {
        PatternImageConfig img_cfg;
        if (from_json) {
          img_cfg.nrows_binned = pimg.nrows_binned;
          img_cfg.ncols        = pimg.ncols;
        } else {
          img_cfg.raw_rows = det.geometry().rows;
          img_cfg.raw_cols = det.geometry().cols;
        }
        img_cfg.row_binning    = pimg.row_binning;
        img_cfg.col_binning    = pimg.col_binning;
        img_cfg.pixel_size_um  = pimg.pixel_size_um;
        img_cfg.sigma_readout_e= pimg.sigma_readout_e;
        img_cfg.lambda_dc      = pimg.lambda_dc;
        img_cfg.rng_seed       = pimg.rng_seed;
        img_cfg.include_dark_current = (pimg.lambda_dc > 0.0);
        auto img_gen_eff = std::make_shared<PatternImageGenerator>(img_cfg, ct);
        emc_ptr->SetPatternImageGenerator(img_gen_eff);
        std::cout << "[scan-pattern] Pattern efficiency will be computed from 2D image (notebook-style, with isolation).\n";
      }
    }

    // =========================================================================
    // 6. Compute ε(n_e): run EfficiencyMC (with optional CSV weights)
    //    PrecomputeEpsilon runs N_trials MC events per n_e value.
    //    PrecomputeEpsilonWithPatternEff folds in the loaded CSV weights.
    //    The result h_eps_ne is a TH1D: bin content = ε for each n_e.
    // =========================================================================
    std::unique_ptr<TH1D> h_eps_ne;

    const double Ee_ref_eV = 50.0;  // reference energy for EfficiencyMC

    auto t_eff_start = std::chrono::steady_clock::now();
    if (!pattern_eff_map.empty()) {
      h_eps_ne = emc_ptr->PrecomputeEpsilonWithPatternEff(
          ne_min_bkg, ne_max, Ee_ref_eV, pattern_eff_map);
      std::cout << "[scan-pattern] Using CSV-weighted pattern efficiencies.\n";
    } else {
      h_eps_ne = emc_ptr->PrecomputeEpsilon(ne_min_bkg, ne_max, Ee_ref_eV);
      std::cout << "[scan-pattern] Using pure EfficiencyMC efficiencies.\n";
    }
    auto t_eff_end = std::chrono::steady_clock::now();
    double t_eff_s = std::chrono::duration<double>(t_eff_end - t_eff_start).count();
    std::cout << "[scan-pattern] Pattern efficiency computation took " << std::fixed << std::setprecision(2) << t_eff_s << " s\n";

    // Optional debug: print ε(n_e) at the reference energy
    std::cout << "[scan-pattern] Precomputed pattern efficiency ε(n_e) at E = "
              << Ee_ref_eV << " eV:\n";
    for (int ne = ne_min; ne <= ne_max; ++ne) {
      int bin = h_eps_ne->FindBin(ne);
      double eps = h_eps_ne->GetBinContent(bin);
      std::cout << "  n_e = " << ne << "  ε = " << eps << "\n";
    }

    // =========================================================================
    // 7. DetectorResponsePipeline wiring
    //    PCDBasedResponse + PCDCalculator handle charge-collection distribution
    //    smearing. The pipeline is configured for Pattern analysis space;
    //    energy-dependent ε(E, n_e) is disabled (use fixed ε(n_e) from above).
    // =========================================================================
    // ---------------- PCD response (for detector smearing) -------------------
    PixelSimulatorConfig pix_cfg_pcd;
    pix_cfg_pcd.mode            = PixelSimMode::LocalPatch;
    pix_cfg_pcd.nx              = 5;
    pix_cfg_pcd.ny              = 5;
    pix_cfg_pcd.pixel_size_um   = det.geometry().pixel_size_um;
    // pix_cfg_pcd.lambda_dc       = lambda_per_exp;
    pix_cfg_pcd.lambda_dc       = 0.0;
    pix_cfg_pcd.sigma_readout_e = emj.sigma_readout_e;
    pix_cfg_pcd.rng_seed        = emj.rng_seed;

    PCDResponseConfig pcd_cfg;
    pcd_cfg.q_min     = cfg.response().pcd.q_min;
    pcd_cfg.q_max     = cfg.response().pcd.q_max;
    pcd_cfg.nbins     = cfg.response().pcd.nbins;
    pcd_cfg.mc_trials = cfg.response().pcd.mc_trials;
    pcd_cfg.pix_cfg   = pix_cfg_pcd;

    auto pcdresp = std::make_shared<PCDBasedResponse>(pcd_cfg, ct);
    auto pcdcalc = std::make_shared<PCDCalculator>();

    DetectorResponsePipeline pipe(ion);

    // Diffusion: only used when PCD is not available (fallback path). When PCD
    // is set, the kernel already includes diffusion; pipeline does not call diff_.
    auto diff = std::make_shared<Diffusion>(
        ct_cfg.A_um2, ct_cfg.b_umInv, ct_cfg.alpha, ct_cfg.beta_per_keV,
        ct_cfg.thickness_um, 0.08, emj.sigma_readout_e);
    pipe.SetDiffusion(diff);
    pipe.SetPCDBasedResponse(pcdresp);
    pipe.SetPCDCalculator(pcdcalc);
    pipe.SetPCDKernelParams(pcc.sigma_res_e, 4.4, 3.125);
    pipe.SetAnalysisSpace(AnalysisSpace::Pattern);

    // Energy-independent pattern ε(n_e) from CSV + EfficiencyMC
    auto pe = std::make_shared<PatternEfficiency>();
    pe->SetEfficiencyHist(*h_eps_ne);   // or whatever your PatternEfficiency uses
    pipe.SetPatternEfficiency(pe);
    pipe.SetSkipPatternEfficiency(use_pattern_bins);

    // We are NOT using E-dependent pattern ε(E, n_e) here
    pipe.EnableEDependentPattern(false);


    // =========================================================================
    // 8. Background model
    //    BackgroundBuilder assembles B_pat from:
    //      • Dark current (lambda_e_per_pix_per_year × livetime × geometry)
    //      • Flat d.r.u. background folded through migration matrix
    //    In pattern space the DC contribution is folded through ε(pattern|n_e).
    //    Alternatively, a pre-computed Bp/Br template can be loaded directly
    //    via run.background_source = "bp_br_template".
    // =========================================================================
    BackgroundBuilder bld(det.geometry().rows,
                          det.geometry().cols,
                          det.geometry().active_fraction,
                          ne_min_bkg, ne_max);

    TimingConfig tcfg;
    tcfg.exposure_time_s = cfg.timing().exposure_time_s;
    if (cfg.timing().n_exposures_override.has_value())
      tcfg.n_exposures_override = cfg.timing().n_exposures_override;
    bld.SetTiming(cfg.experiment_cfg().livetime_days,
                  cfg.experiment_cfg().duty_cycle,
                  tcfg);

    DarkCurrentConfig dcc;
    dcc.lambda_e_per_pix_per_year = cfg.backgrounds().lambda_e_per_pix_per_year;
    dcc.norm_scale                = cfg.backgrounds().norm_scale;
    bld.SetDarkCurrent(dcc);
    if (!use_pattern_bins) bld.SetPatternEfficiency(pe);

    // DC background in pattern space folded with ε(E, n_e)
    // auto B_dc_ne = bld.BuildBkgAsimov_EDependent(
    //     emc_ptr->energy_grid_eV(),
    //     emc_ptr->epsilon_Ene()
    // );  // TH1D in n_e

    auto B_dc_ne = bld.BuildBkgAsimov();

    // Flat background: build via pipeline in pattern space
    const auto& mj = cfg.model();
    DMElectronConfig mc_base;
    mc_base.material          = mj.material;
    mc_base.mediator          = mj.mediator;
    mc_base.rates_dir         = mj.rates_dir;
    mc_base.filename_template = mj.filename_template;
    mc_base.Emin_eV           = mj.Emin_eV;
    mc_base.Emax_eV           = mj.Emax_eV;
    mc_base.nbins             = mj.nbins;

    DMElectronConfig mc_dummy = mc_base;
    mc_dummy.mchi_MeV         = 1.0;
    mc_dummy.sigma_e_cm2      = "1e-40";

    DMElectronModel dm_dummy;
    dm_dummy.Configure(mc_dummy);
    auto dRdE_flat = dm_dummy.MakeSpectrum_E();
    dRdE_flat->Reset("ICES");

    double flat_rate_per_eV = 0.0;
    if (cfg.backgrounds().has_flat_bkg) {
      flat_rate_per_eV =
          cfg.backgrounds().flat_bkg_norm_per_kg_year / 1000.0;
    }
    for (int ib = 1; ib <= dRdE_flat->GetNbinsX(); ++ib) {
      dRdE_flat->SetBinContent(ib, flat_rate_per_eV);
    }

    pipe.SetAnalysisSpace(AnalysisSpace::Pattern);
    // In pattern mode use true n_e for background too: ε(pattern|n_true) already has diffusion.
    // So flat background: ion->FoldToNe (true n_e), not pipe.Apply (reconstructed).
    std::unique_ptr<TH1D> B_flat_ne;
    if (use_pattern_bins) {
      B_flat_ne = ion->FoldToNe(*dRdE_flat, summary.exposure_kg_year, ne_min_bkg, ne_max);
    } else {
      B_flat_ne = pipe.Apply(*dRdE_flat,
                             summary.exposure_kg_year,
                             ne_min_bkg,
                             ne_max,
                             Ee_ref_eV);
    }

    // Total background in n_e (true n_e when use_pattern_bins)
    auto B_tot = std::make_unique<TH1D>(*B_dc_ne);
    if (B_flat_ne) B_tot->Add(B_flat_ne.get());

    // Pattern-space observable: require pattern_roi; efficiency from CSV or from EfficiencyMC
    std::vector<double> B_pat;
    std::unique_ptr<ccdarksens::stats::ProfileLikelihood> profile_pl;
    std::vector<double> profile_S_null;
    std::vector<double> data_for_output;
    if (use_pattern_bins) {
      if (run.background_source != "bp_br_template") {
        // Total background in n_e before pattern folding (includes n_e=0)
        std::cout << "\n[scan-pattern] Total background B_tot(n_e) before pattern fold (includes n_e=0):\n";
        std::cout << std::scientific;
        for (int ne = ne_min_bkg; ne <= ne_max; ++ne) {
          int bin = B_tot->FindBin(static_cast<double>(ne));
          double b = B_tot->GetBinContent(bin);
          std::cout << "  n_e = " << std::setw(2) << ne << "  B_tot = " << b << "\n";
        }
        double B_int = B_tot->Integral();
        std::cout << "  integral = " << B_int << " events\n";
        std::cout << std::defaultfloat;
        double B_roi = 0.0;
        for (int ne : summary.roi_bins) {
          int bin = B_tot->FindBin(ne);
          B_roi += B_tot->GetBinContent(bin);
        }
        std::cout << "  ROI sum (roi_bins) B = " << B_roi << "\n\n";
      }

      if (summary.pattern_roi.empty()) {
        throw std::runtime_error("observable_bins is 'pattern' but experiment.pattern_roi is empty.");
      }
      // If no CSV was loaded, fill pattern efficiencies from EfficiencyMC (same binning as pipeline)
      if (pattern_eff_map.empty()) {
        const auto& table = emc_ptr->GetPatternTable();
        for (const auto& ne_entry : table) {
          int ne = ne_entry.first;
          for (const auto& label_prob : ne_entry.second) {
            int code = 0;
            for (int d : label_prob.first.q) code = code * 10 + d;
            pattern_eff_map[{code, ne}] = label_prob.second;
          }
        }
        std::cout << "[scan-pattern] Filled pattern efficiencies from EfficiencyMC ("
                  << pattern_eff_map.size() << " entries) for observable_bins=pattern.\n";
        std::cout << "[scan-pattern] pattern_roi (all requested):";
        for (int pid : summary.pattern_roi) std::cout << " " << pid;
        std::cout << "\n";
        std::set<int> produced;
        for (const auto& kv : pattern_eff_map) {
          if (kv.second > 0.0) produced.insert(kv.first.first);
        }
        std::cout << "[scan-pattern] Patterns with non-zero P(pattern|n_e) from MC:";
        for (int p : produced) std::cout << " " << p;
        if (produced.empty()) std::cout << " (none)";
        std::cout << "\n";
        std::set<int> requested(summary.pattern_roi.begin(), summary.pattern_roi.end());
        bool missing = false;
        for (int p : requested) {
          if (produced.find(p) == produced.end()) {
            if (!missing) std::cout << "[scan-pattern] Patterns in pattern_roi with 0 efficiency (not produced by MC):";
            std::cout << " " << p;
            missing = true;
          }
        }
        if (missing) std::cout << "\n";
      }
      if (pattern_eff_map.empty()) {
        throw std::runtime_error("observable_bins is 'pattern' but no pattern efficiencies (no CSV and EfficiencyMC table empty).");
      }
      // Optional: overlay with reference efficiencies when generating from MC (fixes efficiency mismatch)
      if (const json* j_emc_ref = EfficiencyMcJsonBlock(jroot);
          j_emc_ref && j_emc_ref->contains("efficiency_csv_reference")) {
        std::string ref_path =
            (*j_emc_ref)["efficiency_csv_reference"].get<std::string>();
        if (!ref_path.empty()) {
          std::filesystem::path ref_to_open(ref_path);
          if (!ref_to_open.is_absolute()) {
            std::filesystem::path config_dir =
                std::filesystem::absolute(std::filesystem::path(config_path)).parent_path();
            ref_to_open = (config_dir / ".." / ref_path).lexically_normal();
          }
          std::ifstream ref_in(ref_to_open.string());
          if (!ref_in.is_open())
            throw std::runtime_error("Failed to open efficiency_csv_reference: " + ref_to_open.string());
          std::string ref_line;
          std::size_t n_ref = 0;
          while (std::getline(ref_in, ref_line)) {
            while (!ref_line.empty() && std::isspace(static_cast<unsigned char>(ref_line.front())))
              ref_line.erase(ref_line.begin());
            if (ref_line.empty() || ref_line[0] == '#' || ref_line.rfind("pattern", 0) == 0) continue;
            std::stringstream rss(ref_line);
            std::string rc;
            int rp = 0, rn = 0;
            double re = 0.0;
            if (!std::getline(rss, rc, ',')) continue;
            try { rp = std::stoi(rc); } catch (...) { continue; }
            if (!std::getline(rss, rc, ',')) continue;
            try { rn = std::stoi(rc); } catch (...) { continue; }
            if (!std::getline(rss, rc, ',')) continue;
            try { re = std::stod(rc); } catch (...) { continue; }
            pattern_eff_map[{rp, rn}] = re;
            ++n_ref;
          }
          std::cout << "[scan-pattern] Overlaid " << n_ref
                    << " (pattern,ne) from reference " << ref_to_open.string() << "\n";
        }
      }
      // Write efficiencies to CSV (pattern, ne, efficiency) for pattern_roi and roi_bins (ne) to match reference format
      std::string eff_csv_path = run.outdir + "/efficiency_per_pattern.csv";
      std::ofstream eff_out(eff_csv_path);
      if (eff_out.is_open()) {
        eff_out << "pattern,ne,Efficiency\n";
        for (int pid : summary.pattern_roi) {
          for (int ne : summary.roi_bins) {
            auto it = pattern_eff_map.find({pid, ne});
            double eff = (it != pattern_eff_map.end()) ? it->second : 0.0;
            eff_out << pid << "," << ne << "," << std::scientific << eff << "\n";
          }
        }
        eff_out.close();
        std::cout << "[scan-pattern] Efficiency table written to " << eff_csv_path << " (pattern_roi × roi_bins)\n";
      }
      // B_pat: either pydme-style Bp+Br template or DC+flat then migration/signal epsilon
      if (run.background_source == "bp_br_template") {
        if (run.background_Bp.size() != summary.pattern_roi.size() ||
            run.background_Br.size() != summary.pattern_roi.size())
          throw std::runtime_error("background_source is bp_br_template but background_Bp/Br size ("
                                  + std::to_string(run.background_Bp.size()) + "/" + std::to_string(run.background_Br.size())
                                  + ") != pattern_roi size (" + std::to_string(summary.pattern_roi.size()) + ")");
        B_pat.resize(summary.pattern_roi.size());
        for (size_t i = 0; i < B_pat.size(); ++i)
          B_pat[i] = run.background_Bp[i] + run.background_Br[i];
        std::cout << "[scan-pattern] B_pat from pydme-style Bp+Br template (background_source=bp_br_template).\n";
      } else {
      const std::string& bkg_eff_csv = cfg.backgrounds().background_efficiency_csv;
      if (!bkg_eff_csv.empty()) {
        // Background fold via migration matrix P(identified | true pattern)
        std::map<std::pair<int, int>, double> migration_map;
        std::ifstream mig_in(bkg_eff_csv);
        if (!mig_in.is_open())
          throw std::runtime_error("Failed to open background efficiency CSV: " + bkg_eff_csv);
        std::string header_line;
        if (!std::getline(mig_in, header_line))
          throw std::runtime_error("Empty background efficiency CSV: " + bkg_eff_csv);
        std::vector<int> iden_codes;
        {
          std::stringstream hs(header_line);
          std::string tok;
          bool first = true;
          while (std::getline(hs, tok, ',')) {
            while (!tok.empty() && std::isspace(static_cast<unsigned char>(tok.back()))) tok.pop_back();
            while (!tok.empty() && std::isspace(static_cast<unsigned char>(tok.front()))) tok.erase(tok.begin());
            if (first) { first = false; continue; }
            if (tok.empty() || tok.rfind("eff_", 0) != 0) continue;
            try {
              int code = std::stoi(tok.substr(4));
              iden_codes.push_back(code);
            } catch (...) { continue; }
          }
        }
        std::string row_line;
        while (std::getline(mig_in, row_line)) {
          while (!row_line.empty() && std::isspace(static_cast<unsigned char>(row_line.front())))
            row_line.erase(row_line.begin());
          if (row_line.empty()) continue;
          std::stringstream rs(row_line);
          std::string first_col;
          if (!std::getline(rs, first_col, ',')) continue;
          int true_pat = 0;
          try { true_pat = std::stoi(first_col); } catch (...) { continue; }
          for (size_t j = 0; j < iden_codes.size(); ++j) {
            std::string cell;
            if (!std::getline(rs, cell, ',')) break;
            try {
              double p = std::stod(cell);
              migration_map[{true_pat, iden_codes[j]}] = p;
            } catch (...) {}
          }
        }
        std::cout << "[scan-pattern] Loaded background migration matrix: " << migration_map.size()
                  << " (true_pat, iden_pat) entries from " << bkg_eff_csv << "\n";
        // B_true_pat: rate per true (ideal) pattern. DC + flat in n_e → single-pixel patterns 0..5.
        std::map<int, double> B_true_pat;
        for (int ne = 0; ne <= 5; ++ne) {
          int bin = B_tot->FindBin(static_cast<double>(ne));
          double rate = B_tot->GetBinContent(bin);
          if (rate != 0.0) B_true_pat[ne] = rate;
        }
        B_pat = ccdarksens::FoldBackgroundWithMigration(
            B_true_pat, summary.pattern_roi, migration_map);
        std::cout << "[scan-pattern] B_pat from background_efficiency_csv (DC and flat through migration).\n";
      } else {
        // No background CSV: fold DC and flat with signal ε(pattern|n_true).
        std::vector<double> B_dc_pat = ccdarksens::FoldNeToPatternRates(
            *B_dc_ne, ne_min_bkg, ne_max, summary.pattern_roi, pattern_eff_map);
        std::vector<double> B_flat_pat = B_flat_ne
            ? ccdarksens::FoldNeToPatternRates(
                  *B_flat_ne, ne_min_bkg, ne_max, summary.pattern_roi, pattern_eff_map)
            : std::vector<double>(summary.pattern_roi.size(), 0.0);
        B_pat.resize(B_dc_pat.size());
        for (size_t i = 0; i < B_pat.size(); ++i) B_pat[i] = B_dc_pat[i] + B_flat_pat[i];
      }
      }
      std::cout << "[scan-pattern] Observable = pattern bins. pattern_roi size = "
                << summary.pattern_roi.size() << ", B_pat sum = ";
      double B_pat_sum = 0;
      for (double v : B_pat) B_pat_sum += v;
      std::cout << B_pat_sum << "\n\n";

      if (run.use_profile_likelihood) {
        profile_pl = std::make_unique<ccdarksens::stats::ProfileLikelihood>();
        if (run.single_bin_likelihood) {
          double d_sum = 0, b_sum = 0;
          for (double v : B_pat) b_sum += v;
          if (!run.data_path.empty()) {
            auto data = load_data(run.data_path, B_pat.size(), &summary.pattern_roi);
            if (data.size() < B_pat.size())
              throw std::runtime_error("data_path \"" + run.data_path + "\" has " + std::to_string(data.size()) + " values, need " + std::to_string(B_pat.size()));
            for (std::size_t i = 0; i < B_pat.size(); ++i) d_sum += data[i];
          } else {
            d_sum = b_sum;
          }
          profile_pl->SetData({d_sum});
          profile_pl->SetBTemplate({b_sum});
          profile_S_null = {0.0};
          if (run.verbosity >= 1)
            std::cout << "[scan-pattern] Profile likelihood: single-bin, data_sum=" << d_sum << " B_sum=" << b_sum << "\n";
        } else {
          const auto observed_cfg =
              ObservedCountsFromConfig(jroot, summary.pattern_roi);
          if (!observed_cfg.empty()) {
            profile_pl->SetData(observed_cfg);
            data_for_output = observed_cfg;
            if (run.verbosity >= 1) {
              std::cout << "[scan-pattern] Profile likelihood: observed_counts from config "
                           "(overrides data_path)\n";
              for (std::size_t i = 0; i < summary.pattern_roi.size(); ++i)
                std::cout << "  pattern " << summary.pattern_roi[i]
                          << "  D=" << observed_cfg[i] << "\n";
            }
          } else if (!run.data_path.empty()) {
            auto data = load_data(run.data_path, B_pat.size(), &summary.pattern_roi);
            if (data.size() < B_pat.size())
              throw std::runtime_error("data_path \"" + run.data_path + "\" has " + std::to_string(data.size()) + " values, need " + std::to_string(B_pat.size()));
            data.resize(B_pat.size());
            profile_pl->SetData(data);
            data_for_output = data;
            double data_exposure = 0.0;
            const bool has_data_exposure = get_exposure_from_data_file(run.data_path, &data_exposure);
            const double cfg_exposure = summary.exposure_kg_year;
            if (has_data_exposure) {
              if (cfg_exposure > 0.0) {
                const double rel = std::abs(data_exposure - cfg_exposure) / cfg_exposure;
                if (rel > 0.01)
                  std::cout << "[scan-pattern] WARNING: data file exposure_kg_year = " << std::scientific << data_exposure
                            << " but config gives " << cfg_exposure << std::defaultfloat
                            << " (relative diff " << (rel * 100) << "%). "
                            << "Set experiment.livetime_days and detector mass to match data for correct S_pat/B_pat.\n";
                else if (run.verbosity >= 1)
                  std::cout << "[scan-pattern] Data exposure_kg_year = " << data_exposure << " (matches config).\n";
              } else if (data_exposure > 0.0)
                std::cout << "[scan-pattern] WARNING: data file has exposure_kg_year = " << std::scientific << data_exposure
                          << " but config exposure is 0 (check experiment.livetime_days and detector.mass_kg).\n" << std::defaultfloat;
            } else if (run.verbosity >= 1)
              std::cout << "[scan-pattern] Data file has no exposure_kg_year (scan uses config exposure = "
                        << std::scientific << cfg_exposure << " kg·year).\n" << std::defaultfloat;
            if (run.verbosity >= 1) {
              std::cout << "[scan-pattern] Profile likelihood: real data from " << run.data_path
                        << " (mapped by pattern label to pattern_roi)\n";
              for (std::size_t i = 0; i < summary.pattern_roi.size() && i < data.size(); ++i)
                std::cout << "  pattern " << summary.pattern_roi[i] << "  D=" << data[i] << "\n";
            }
          } else {
            profile_pl->SetData(B_pat);
            if (run.verbosity >= 1)
              std::cout << "[scan-pattern] Profile likelihood: Asimov (data = B)\n";
          }
          profile_S_null.assign(B_pat.size(), 0.0);
          std::string bg_model = run.background_model;
          if (bg_model == "Bp_theta_Br" || bg_model == "Bp_theta_br") {
            if (run.background_Bp.size() == B_pat.size() && run.background_Br.size() == B_pat.size()) {
              profile_pl->SetBpBr(run.background_Bp, run.background_Br);
              if (run.verbosity >= 1)
                std::cout << "[scan-pattern] Background: B = Bp + theta*Br (from config)\n";
            } else {
              std::vector<double> z(B_pat.size(), 0.0);
              profile_pl->SetBpBr(z, B_pat);
              if (run.verbosity >= 1)
                std::cout << "[scan-pattern] Background: B = theta*Br with Br = B_pat (Bp=0)\n";
            }
            profile_pl->SetConstrainPriorStrength(run.constrain_prior_strength);
            profile_pl->SetConstrainGammaSign(run.constrain_use_gamma_sign);
            profile_pl->SetConstrainUseTauWeighted(run.constrain_use_tau_weighted);
            profile_pl->SetConstrainNBins(run.constrain_n_bins);
            profile_pl->SetAcceptBoundary2DMinimum(run.pydme_style_ul);
            if (run.verbosity >= 1 && run.pydme_style_ul)
              std::cout << "[scan-pattern] pydme_style_ul=true: accept 2D fit at boundary, use 2D nll_min for UL (match pydme).\n";
            if (run.verbosity >= 1)
              std::cout << "[scan-pattern] Stored UL = q(σ) grid crossing (smooth); pydme re-minuit bisection written separately when available.\n";
            if (run.verbosity >= 1 && run.constrain_prior_strength > 0)
              std::cout << "[scan-pattern] Constrain: "
                        << (run.constrain_use_tau_weighted ? "pydme tau-weighted (mode theta=1)" : run.constrain_use_gamma_sign ? "Gamma prior" : "pydme")
                        << " L(theta), prior_strength=" << run.constrain_prior_strength
                        << ", n_bins=" << run.constrain_n_bins << (run.constrain_n_bins > 1 ? " (multi-bin form)" : "") << "\n";
          } else {
            profile_pl->SetBTemplate(B_pat);
          }
        }
        if (run.constrain_scale_prior_mean && run.constrain_scale_prior_sigma && *run.constrain_scale_prior_sigma > 0) {
          const double mean = *run.constrain_scale_prior_mean;
          const double sig  = *run.constrain_scale_prior_sigma;
          profile_pl->SetConstrain([mean, sig](double scale) {
            return 0.5 * std::pow((scale - mean) / sig, 2);
          });
          if (run.verbosity >= 1)
            std::cout << "[scan-pattern] Constrain: Gaussian prior on scale (mean=" << mean << ", sigma=" << sig << ")\n";
        }
      }
    } else {
      // n_e (single-pixel) observable: build B_ne and optionally profile likelihood (data or Asimov)
      std::vector<double> B_ne;
      B_ne.reserve(summary.roi_bins.size());
      for (int ne : summary.roi_bins) {
        int bin = B_tot->FindBin(static_cast<double>(ne));
        B_ne.push_back(B_tot->GetBinContent(bin));
      }
      std::cout << "[scan-pattern] Observable = n_e bins (single-pixel). roi_bins size = "
                << B_ne.size() << ", B_ne sum = ";
      double B_ne_sum = 0;
      for (double v : B_ne) B_ne_sum += v;
      std::cout << B_ne_sum << "\n\n";

      if (run.use_profile_likelihood) {
        profile_pl = std::make_unique<ccdarksens::stats::ProfileLikelihood>();
        if (run.single_bin_likelihood) {
          double d_sum = 0, b_sum = 0;
          for (double v : B_ne) b_sum += v;
          if (!run.data_path.empty()) {
            auto data = load_data(run.data_path, B_ne.size(), &summary.roi_bins);
            if (data.size() < B_ne.size())
              throw std::runtime_error("data_path \"" + run.data_path + "\" has " + std::to_string(data.size()) + " values, need " + std::to_string(B_ne.size()));
            for (std::size_t i = 0; i < B_ne.size(); ++i) d_sum += data[i];
          } else {
            d_sum = b_sum;
          }
          profile_pl->SetData({d_sum});
          profile_pl->SetBTemplate({b_sum});
          profile_S_null = {0.0};
          if (run.verbosity >= 1)
            std::cout << "[scan-pattern] Profile likelihood (n_e): single-bin, data_sum=" << d_sum << " B_sum=" << b_sum << "\n";
        } else {
          if (!run.data_path.empty()) {
            auto data = load_data(run.data_path, B_ne.size(), &summary.roi_bins);
            if (data.size() < B_ne.size())
              throw std::runtime_error("data_path \"" + run.data_path + "\" has " + std::to_string(data.size()) + " values, need " + std::to_string(B_ne.size()));
            data.resize(B_ne.size());
            profile_pl->SetData(data);
            data_for_output = data;
            if (run.verbosity >= 1)
              std::cout << "[scan-pattern] Profile likelihood (n_e): real data from " << run.data_path << "\n";
          } else {
            profile_pl->SetData(B_ne);
            if (run.verbosity >= 1)
              std::cout << "[scan-pattern] Profile likelihood (n_e): Asimov (data = B_ne)\n";
          }
          profile_S_null.assign(B_ne.size(), 0.0);
          // B = theta * B_ne (single nuisance scale)
          std::vector<double> z(B_ne.size(), 0.0);
          profile_pl->SetBpBr(z, B_ne);
          profile_pl->SetConstrainPriorStrength(run.constrain_prior_strength);
          profile_pl->SetConstrainGammaSign(run.constrain_use_gamma_sign);
          profile_pl->SetConstrainUseTauWeighted(run.constrain_use_tau_weighted);
          profile_pl->SetConstrainNBins(run.constrain_n_bins);
          profile_pl->SetAcceptBoundary2DMinimum(run.pydme_style_ul);
          if (run.verbosity >= 1)
            std::cout << "[scan-pattern] Background (n_e): B = theta*B_ne, constrain prior_strength=" << run.constrain_prior_strength << "\n";
        }
        if (run.constrain_scale_prior_mean && run.constrain_scale_prior_sigma && *run.constrain_scale_prior_sigma > 0) {
          const double mean = *run.constrain_scale_prior_mean;
          const double sig  = *run.constrain_scale_prior_sigma;
          profile_pl->SetConstrain([mean, sig](double scale) {
            return 0.5 * std::pow((scale - mean) / sig, 2);
          });
          if (run.verbosity >= 1)
            std::cout << "[scan-pattern] Constrain: Gaussian prior on scale (mean=" << mean << ", sigma=" << sig << ")\n";
        }
      }
    }

    // When not profiling, optionally load real data for q(mchi, sigma) grid (limit from crossing later in plot app)
    std::vector<double> data_for_q_grid;
    if (!profile_pl && !run.data_path.empty()) {
      const size_t expected = use_pattern_bins ? B_pat.size() : summary.roi_bins.size();
      const std::vector<int>& roi_ids =
          use_pattern_bins ? summary.pattern_roi : summary.roi_bins;
      auto loaded = load_data(run.data_path, expected, &roi_ids);
      if (loaded.size() >= expected) {
        loaded.resize(expected);
        data_for_q_grid = std::move(loaded);
        if (run.verbosity >= 1)
          std::cout << "[scan-pattern] Real data loaded from " << run.data_path
                    << " for q-grid (no profiling). Limit from q crossing in plot app.\n";
      }
    }

    // =========================================================================
    // 9. Build (mχ, σ_e) scan grid and output histograms
    //    The grid is expanded from JSON spec (linspace / logspace / values).
    //    h_q stores q(mχ, σ) on the full 2-D grid; h_upper_limit stores the
    //    per-mass 90 % CL UL extracted from the q(σ) crossing.
    //    target_q = Z_α² = [InvNorm(CL)]² (e.g. 2.706 for 90 % CL).
    // =========================================================================
    const auto& jgrid = jroot["model"]["grid"];
    auto mchi_list   = expand_axis(jgrid.at("mchi_MeV"), "mchi_MeV");
    auto sigma_list  = expand_axis(jgrid.at("sigma_e_cm2"), "sigma_e_cm2");

    if (mchi_list.empty() || sigma_list.empty()) {
      throw std::runtime_error("Empty mchi_MeV or sigma_e_cm2 grid.");
    }

    std::string fmt_sigma = ".1e";
    if (jgrid.contains("format")) {
      fmt_sigma = jgrid["format"].value("sigma", std::string(".1e"));
    }

    auto edges_m = make_edges_from_centers(mchi_list);
    auto edges_s = make_edges_from_centers(sigma_list);

    TH2D h_q("q_mchi_sigma_pattern",
             ";m_{#chi} [MeV];#sigma_{e} [cm^{2}];q_{Asimov} (pattern)",
             static_cast<int>(mchi_list.size()), edges_m.data(),
             static_cast<int>(sigma_list.size()), edges_s.data());

    // Profile-likelihood: same minimization and log-likelihood process as pydme (see docs/Log_likelihood_pydme_comparison.md):
    // NLL = Poisson(mu - n*ln(mu)) + constrain(theta); B = Bp + theta*Br; minimize over theta for each S(sigma);
    // q_mu = 2*(nll(sigma) - nll_min); target_q = NormQuantile(CL)^2; UL = smallest sigma with q_mu >= target_q.
    // pydme SRDM uses theta_limits = [[0.5, 10]]; keep theta=1 (nominal B=Bp+Br) inside bounds to avoid boundary effects.
    // q_mu / q0 / upper limit (when use_profile_likelihood): 1D in m_chi
    TH1D h_q0("q0_mchi", ";m_{#chi} [MeV];q_{0}", static_cast<int>(mchi_list.size()), edges_m.data());
    TH1D h_upper_limit("upper_limit_sigma_e_mchi", ";m_{#chi} [MeV];#sigma_{e} [cm^{2}] (90% CL)", static_cast<int>(mchi_list.size()), edges_m.data());
    std::vector<double> ul_pydme_bisection_vals(mchi_list.size(), -1.0);
    const double target_q = profile_pl
        ? std::pow(TMath::NormQuantile(run.cl), 2) : 0.0;
    double profile_param_lo = 0.01, profile_param_hi = 10.0;
    if (profile_pl && profile_pl->UseBpBr()) {
      profile_param_lo = run.theta_lo;
      profile_param_hi = run.theta_hi;
    }

    // Validation histograms (pattern mode): B_pat and S_pat (first grid point) always
    std::unique_ptr<TH1D> h_S_pat_validation;
    std::unique_ptr<TH1D> h_B_pat_validation;
    // Optional per-grid-point dump of spectra (dRdE, S_true, and S_obs/S_pat)
    std::vector<std::unique_ptr<TH1D>> dump_spectra_hists;

    auto sanitize_root_name = [](std::string s) -> std::string {
      for (char& c : s) {
        if (c == '.') c = 'p';
        else if (c == '-') c = 'm';
        else if (c == '+') c = 'p';
        else if (c == 'e' || c == 'E') c = 'e'; // keep
        else if (!(std::isalnum(static_cast<unsigned char>(c)) || c == '_' )) c = '_';
      }
      return s;
    };

    // =========================================================================
    // 10. Main scan loop — compute q(mχ, σ_e) and extract 90 % CL upper limits
    //
    //  For each mχ:
    //    a) Minimise NLL over θ with S=0 to get NLL_null (background-only best-fit).
    //    b) For each σ_e:
    //         i.  Load dR/dE table → fold to S_true(n_e) → fold to S_pat.
    //         ii. Minimise NLL(S+B, θ) over θ with fixed signal.
    //    c) q_μ(σ) = 2·[NLL(σ) − NLL_min]; monotonise; find 90 % CL crossing.
    //
    //  pydme / minuit2d mode performs a single 2-D Minuit fit over (log₁₀σ, θ)
    //  per mχ so that NLL_min is the global minimum (closer to pydme result).
    // =========================================================================
    DMElectronConfig mc_sig_base = mc_base;
    std::cout << std::scientific << std::setprecision(8);

    int idx_mchi = 0;
    for (double mchi : mchi_list) {
      double nll_null = 0.0;
      std::vector<double> nll_values;
      double nll_min_2d = std::numeric_limits<double>::max();
      bool use_2d_nll_min = false;
      double log10_sigma_hat_pydme = std::log10(sigma_list.front());  // for pydme UL bracketing
      std::vector<std::vector<double>> S_grid;
      if (profile_pl && !use_pattern_bins) {
        // n_e mode: minimize over theta at S=0 once per mass; nll_values filled in sigma loop
        double theta_hat_ne = 0.0;
        if (run.profile_minimizer == "minuit" || run.profile_minimizer == "minuit2d" || run.profile_minimizer == "pydme") {
          auto pr = profile_pl->MinimizeOverScaleMinuit(profile_S_null, profile_param_lo, profile_param_hi);
          nll_null = pr.second;
          theta_hat_ne = pr.first;
          std::cout << "[scan-pattern] mchi=" << mchi << " MeV (n_e): minimized theta (S=0) = " << theta_hat_ne << "\n";
        } else {
          auto pr = profile_pl->MinimizeOverScale(profile_S_null, profile_param_lo, profile_param_hi);
          nll_null = pr.second;
          theta_hat_ne = pr.first;
          std::cout << "[scan-pattern] mchi=" << mchi << " MeV (n_e): minimized theta (S=0) = " << theta_hat_ne << "\n";
        }
        {
          const double margin = 0.02 * (profile_param_hi - profile_param_lo);
          if (theta_hat_ne <= profile_param_lo + margin) {
            std::cout << "[scan-pattern] WARNING (n_e): theta is at the LOWER bound (theta_lo). Consider constrain_prior_strength or theta_lo/theta_hi.\n";
          } else if (theta_hat_ne >= profile_param_hi - margin) {
            std::cout << "[scan-pattern] WARNING (n_e): theta is at the UPPER bound (theta_hi). Consider extending theta_hi or constrain settings.\n";
          }
        }
        nll_values.reserve(sigma_list.size());
      } else if (profile_pl && use_pattern_bins) {
        double theta_hat_1d = 0.0;
        if (run.profile_minimizer == "minuit" || run.profile_minimizer == "minuit2d" || run.profile_minimizer == "pydme") {
          auto pr = profile_pl->MinimizeOverScaleMinuit(profile_S_null, profile_param_lo, profile_param_hi);
          nll_null = pr.second;
          theta_hat_1d = pr.first;
          std::cout << "[scan-pattern] mchi=" << mchi << " MeV: minimized theta (S=0) = " << theta_hat_1d << "\n";
        } else {
          auto pr_brent = profile_pl->MinimizeOverScale(profile_S_null, profile_param_lo, profile_param_hi);
          nll_null = pr_brent.second;
          theta_hat_1d = pr_brent.first;
          std::cout << "[scan-pattern] mchi=" << mchi << " MeV: minimized theta (S=0) = " << theta_hat_1d << "\n";
        }
        {
          const double margin = 0.02 * (profile_param_hi - profile_param_lo);
          if (theta_hat_1d <= profile_param_lo + margin) {
            std::cout << "[scan-pattern] WARNING: theta is at the LOWER bound (theta_lo). This often happens when:\n"
                         "  - The constraint prior has its mode above theta_hi (e.g. 98/sum(Br)), so it pushes theta down in [theta_lo, theta_hi].\n"
                         "  - Data exposure is much smaller than config exposure (data and B_pat on different scales).\n"
                         "  Consider: set constrain_prior_strength=0 to see unconstrained best-fit, or fix experiment/detector to match data.\n";
          } else if (theta_hat_1d >= profile_param_hi - margin) {
            std::cout << "[scan-pattern] WARNING: theta is at the UPPER bound (theta_hi). This often happens when:\n"
                         "  - Gamma prior (constrain_use_gamma_sign=true) has mode ~ prior_strength*n_bins/sum(Br) above theta_hi.\n"
                         "  Consider: extend theta_hi so the prior mode is inside [theta_lo, theta_hi], or use constrain_use_gamma_sign=false.\n";
          }
        }
        nll_values.reserve(sigma_list.size());

        // Pydme-style: one 2D Minuit over (log10(sigma_e), theta) per mchi; nll_min from that fit.
        const bool do_2d_fit = (run.profile_minimizer == "minuit2d" || run.profile_minimizer == "pydme") && sigma_list.size() >= 2u;
        if (do_2d_fit) {
          S_grid.reserve(sigma_list.size());
          for (double sigma_val : sigma_list) {
            DMElectronConfig mc = mc_sig_base;
            mc.mchi_MeV = mchi;
            mc.sigma_e_cm2 = format_sigma(sigma_val, fmt_sigma);
            DMElectronModel dm_sig;
            if (!dm_sig.Configure(mc)) {
              const size_t nbin = run.single_bin_likelihood ? 1u : B_pat.size();
              S_grid.push_back(std::vector<double>(nbin, 0.0));
              continue;
            }
            auto dRdE_sig = dm_sig.MakeSpectrum_E();
            pipe.SetAnalysisSpace(AnalysisSpace::Pattern);
            auto S_true = ion->FoldToNe(*dRdE_sig, summary.exposure_kg_year, ne_min, ne_max);
            std::vector<double> S_pat = ccdarksens::FoldNeToPatternRates(
                *S_true, ne_min, ne_max, summary.pattern_roi, pattern_eff_map);
            if (run.single_bin_likelihood) {
              double s_sum = 0;
              for (double x : S_pat) s_sum += x;
              S_grid.push_back({s_sum});
            } else {
              S_grid.push_back(S_pat);
            }
          }
          const double log10_lo = std::log10(sigma_list.front());
          const double log10_hi = std::log10(sigma_list.back());
          auto S_from_log10 = [&S_grid, &sigma_list, log10_lo, log10_hi](double log10_s) -> std::vector<double> {
            const size_t n = S_grid.empty() ? 0u : S_grid[0].size();
            std::vector<double> out(n, 0.0);
            if (S_grid.size() < 2u) return S_grid.empty() ? out : S_grid[0];
            const double log10_s_clamp = std::max(log10_lo, std::min(log10_hi, log10_s));
            for (size_t j = 0; j + 1 < sigma_list.size(); ++j) {
              const double l0 = std::log10(sigma_list[j]);
              const double l1 = std::log10(sigma_list[j + 1]);
              if (log10_s_clamp >= l0 && log10_s_clamp <= l1) {
                const double t = (l1 - l0) > 1e-300 ? (log10_s_clamp - l0) / (l1 - l0) : 0.0;
                for (size_t b = 0; b < n; ++b)
                  out[b] = S_grid[j][b] + t * (S_grid[j + 1][b] - S_grid[j][b]);
                return out;
              }
            }
            if (log10_s_clamp <= std::log10(sigma_list[0])) return S_grid[0];
            return S_grid.back();
          };
          auto result = profile_pl->MinimizeOverSigmaAndTheta(
              S_from_log10, log10_lo, log10_hi, profile_param_lo, profile_param_hi);
          if (result.ok) {
            nll_min_2d = result.nll_min;
            use_2d_nll_min = true;
            log10_sigma_hat_pydme = result.log10_sigma_hat;
            if (run.verbosity >= 1)
              std::cout << "[scan-pattern] mchi=" << mchi << " MeV " << run.profile_minimizer
                        << ": log10_sigma_hat=" << result.log10_sigma_hat
                        << " theta_hat=" << result.theta_hat << " nll_min=" << result.nll_min << "\n";
          }
        }
      }

      int idx_sigma = 0;
      for (double sigma_val : sigma_list) {

        // minuit2d / pydme: use precomputed S_grid; skip DM + fold for this sigma.
        if (profile_pl && use_pattern_bins && (run.profile_minimizer == "minuit2d" || run.profile_minimizer == "pydme") && !S_grid.empty() && idx_sigma < static_cast<int>(S_grid.size())) {
          const std::vector<double>& S_for_pl = S_grid[idx_sigma];
          double nll;
          if (run.profile_minimizer == "minuit" || run.profile_minimizer == "minuit2d" || run.profile_minimizer == "pydme") {
            const double nll_m = profile_pl->MinimizeOverScaleMinuit(S_for_pl, profile_param_lo, profile_param_hi).second;
            const double nll_b = profile_pl->MinimizeOverScale(S_for_pl, profile_param_lo, profile_param_hi).second;
            nll = std::min(nll_m, nll_b);
          } else {
            nll = profile_pl->MinimizeOverScale(S_for_pl, profile_param_lo, profile_param_hi).second;
          }
          nll_values.push_back(nll);
          ++idx_sigma;
          continue;
        }

        DMElectronConfig mc = mc_sig_base;
        mc.mchi_MeV    = mchi;
        mc.sigma_e_cm2 = format_sigma(sigma_val, fmt_sigma);

        DMElectronModel dm_sig;
        if (!dm_sig.Configure(mc)) {
          std::cerr << "[scan-pattern] WARNING: failed to configure DM model for "
                    << "mchi=" << mchi
                    << ", sigma=" << sigma_val << "\n";
          h_q.SetBinContent(idx_mchi + 1, idx_sigma + 1, 0.0);
          ++idx_sigma;
          continue;
        }
        std::cout << "[scan-pattern] Scanning mchi=" << mchi
                  << " MeV, sigma=" << sigma_val << " cm^2\n";

        auto dRdE_sig = dm_sig.MakeSpectrum_E();

        pipe.SetAnalysisSpace(AnalysisSpace::Pattern);
        // Pattern mode: we only need S_true; ε(pattern|n_true) already encodes full detector.
        // n_e mode: same treatment — FoldToNe + ε(n_e) only; no PCD/diffusion (avoids extra scalings).
        auto S_true = ion->FoldToNe(*dRdE_sig, summary.exposure_kg_year, ne_min, ne_max);
        std::unique_ptr<TH1D> S_obs;
        if (!use_pattern_bins) {
          S_obs = std::make_unique<TH1D>(*S_true);
          for (int i = 1; i <= S_obs->GetNbinsX(); ++i) {
            const double ne = S_obs->GetBinCenter(i);
            const int b_eps = h_eps_ne->FindBin(ne);
            const double e = std::clamp(h_eps_ne->GetBinContent(b_eps), 0.0, 1.0);
            S_obs->SetBinContent(i, S_obs->GetBinContent(i) * e);
          }
        }

        // Optional: dump per-point spectra to the output ROOT file.
        // We store clones here and write them when creating the output file later.
        if (run.dump_point_spectra_root) {
          const std::string mchi_tag  = sanitize_root_name("mchi_" + format_double(mchi, ".6f"));
          const std::string sig_tag   = sanitize_root_name("sigma_" + format_sigma(sigma_val, fmt_sigma));
          const std::string point_tag = mchi_tag + "__" + sig_tag;

          // dR/dE in events/(kg·year·eV)
          auto h_dRdE = std::make_unique<TH1D>(*dRdE_sig);
          h_dRdE->SetName(("dRdE__" + point_tag).c_str());
          h_dRdE->SetTitle(("dR/dE;E_{e} [eV];events/(kg year eV) (" + point_tag + ")").c_str());
          dump_spectra_hists.push_back(std::move(h_dRdE));

          // S_true(n_e) counts in exposure
          auto h_S_true = std::make_unique<TH1D>(*S_true);
          h_S_true->SetName(("S_true_ne__" + point_tag).c_str());
          h_S_true->SetTitle(("S_{true}(n_{e});n_{e};expected counts (" + point_tag + ")").c_str());
          dump_spectra_hists.push_back(std::move(h_S_true));

          if (use_pattern_bins) {
            // Pattern-space expected counts (Spat) computed from S_true via ε(pattern|n_true)
            std::vector<double> S_pat_dump = ccdarksens::FoldNeToPatternRates(
                *S_true, ne_min, ne_max, summary.pattern_roi, pattern_eff_map);
            const int np = static_cast<int>(summary.pattern_roi.size());
            auto h_S_pat = std::make_unique<TH1D>(
                ("S_pat__" + point_tag).c_str(),
                ("S_{pat};pattern bin;expected counts (" + point_tag + ")").c_str(),
                np, 0.5, np + 0.5);
            for (int i = 0; i < np; ++i) {
              h_S_pat->SetBinContent(i + 1, (i < static_cast<int>(S_pat_dump.size())) ? S_pat_dump[i] : 0.0);
              h_S_pat->GetXaxis()->SetBinLabel(i + 1, std::to_string(summary.pattern_roi[i]).c_str());
            }
            dump_spectra_hists.push_back(std::move(h_S_pat));
          } else if (S_obs) {
            auto h_S_obs = std::make_unique<TH1D>(*S_obs);
            h_S_obs->SetName(("S_obs_ne__" + point_tag).c_str());
            h_S_obs->SetTitle(("S_{obs}(n_{e});n_{e};expected counts (" + point_tag + ")").c_str());
            dump_spectra_hists.push_back(std::move(h_S_obs));
          }
        }

        // Compute q-statistic: either n_e ROI bins or pattern bins
        ccdarksens::stats::StatisticsConfig stats_cfg;
        stats_cfg.test_stat = "PLR";
        stats_cfg.verbosity = 0;

        auto ts = ccdarksens::stats::MakeTestStatistic(stats_cfg);
        if (!ts) {
          throw std::runtime_error("Failed to construct test statistic (PLR).");
        }
        std::vector<double> data;
        std::vector<double> model_null;
        std::vector<double> model_test;
        double q_ts = 0.0;

        if (use_pattern_bins) {
          // Use S_true (not S_obs): ε(pattern|n_true) already encodes full detector; folding with S_obs would double-count.
          std::vector<double> S_pat = ccdarksens::FoldNeToPatternRates(
              *S_true, ne_min, ne_max, summary.pattern_roi, pattern_eff_map);
          data = (!data_for_q_grid.empty()) ? data_for_q_grid : B_pat;
          model_null = B_pat;
          model_test.resize(B_pat.size());
          for (size_t i = 0; i < B_pat.size(); ++i)
            model_test[i] = S_pat[i] + B_pat[i];

          if (idx_mchi == 0 && idx_sigma == 0 && run.verbosity >= 1) {
            double S_pat_sum = 0;
            for (double x : S_pat) S_pat_sum += x;
            std::cout << "[scan-pattern] First grid point: exposure_kg_year = " << summary.exposure_kg_year
                      << ", S_pat_sum = " << S_pat_sum << " (signal scales with exposure; re-run scan after changing livetime_days/mass_kg)\n";
          }
          // Validation output for first grid point (skip when minuit2d: we use precomputed S_grid).
          if (idx_mchi == 0 && idx_sigma == 0 && run.profile_minimizer != "minuit2d" && run.profile_minimizer != "pydme") {
            std::cout << "\n[scan-pattern] === Validation (single case: first grid point) ===\n";
            std::cout << "  mchi = " << mchi << " MeV, sigma = " << sigma_val << " cm^2\n";
            std::cout << "  S_true(n_e) [used for pattern fold; avoids double-counting with ε(pattern|n_true)]:\n";
            for (int ne = ne_min; ne <= ne_max; ++ne) {
              int bin = S_true->FindBin(static_cast<double>(ne));
              double v = S_true->GetBinContent(bin);
              if (v != 0.0)
                std::cout << "    n_e = " << ne << "  S_true = " << v << "\n";
            }
            std::cout << "  Pattern bins (pattern_roi | S_pat | B_pat | model_test = S+B):\n";
            for (size_t i = 0; i < summary.pattern_roi.size(); ++i) {
              std::cout << "    pattern " << summary.pattern_roi[i]
                        << "  S_pat = " << S_pat[i]
                        << "  B_pat = " << B_pat[i]
                        << "  model_test = " << model_test[i] << "\n";
            }
            const int np = static_cast<int>(summary.pattern_roi.size());
            h_S_pat_validation = std::make_unique<TH1D>("S_pat_validation",
                "Signal rate per pattern (first grid point);pattern bin;rate",
                np, 0.5, np + 0.5);
            h_B_pat_validation = std::make_unique<TH1D>("B_pat_validation",
                "Background rate per pattern;pattern bin;rate",
                np, 0.5, np + 0.5);
            for (int i = 0; i < np; ++i) {
              h_S_pat_validation->SetBinContent(i + 1, S_pat[i]);
              h_B_pat_validation->SetBinContent(i + 1, B_pat[i]);
              h_S_pat_validation->GetXaxis()->SetBinLabel(i + 1, std::to_string(summary.pattern_roi[i]).c_str());
              h_B_pat_validation->GetXaxis()->SetBinLabel(i + 1, std::to_string(summary.pattern_roi[i]).c_str());
            }
            if (run.data_path.empty())
              std::cout << "  (Histograms S_pat_validation, B_pat_validation written to output ROOT file.)\n\n";
            else
              std::cout << "  (Data mode: D_pat, S_pat_validation, B_pat_validation written to output ROOT file.)\n\n";
          }
          if (profile_pl) {
            std::vector<double> S_for_pl;
            if (run.profile_minimizer == "minuit2d" && !S_grid.empty() && idx_sigma < static_cast<int>(S_grid.size())) {
              S_for_pl = S_grid[idx_sigma];
            } else if (run.single_bin_likelihood) {
              double s_sum = 0;
              for (double x : S_pat) s_sum += x;
              S_for_pl = {s_sum};
            } else {
              S_for_pl = S_pat;
            }
            double nll;
            if (run.profile_minimizer == "minuit") {
              const double nll_m = profile_pl->MinimizeOverScaleMinuit(S_for_pl, profile_param_lo, profile_param_hi).second;
              const double nll_b = profile_pl->MinimizeOverScale(S_for_pl, profile_param_lo, profile_param_hi).second;
              nll = std::min(nll_m, nll_b);  // use best of both so profile is never worse than Brent
            } else {
              nll = profile_pl->MinimizeOverScale(S_for_pl, profile_param_lo, profile_param_hi).second;
            }
            nll_values.push_back(nll);
            q_ts = 0.0;  // will overwrite with q_mu after loop
          } else {
            q_ts = ts->EvaluateRatio(data, model_test, model_null);
          }
        } else {
          data.reserve(summary.roi_bins.size());
          model_null.reserve(summary.roi_bins.size());
          model_test.reserve(summary.roi_bins.size());
          if (profile_pl) {
            // n_e profile: build S_for_pl from S_obs and minimize over theta
            std::vector<double> S_for_pl;
            S_for_pl.reserve(summary.roi_bins.size());
            for (int ne : summary.roi_bins) {
              int bin = S_obs->FindBin(static_cast<double>(ne));
              S_for_pl.push_back(S_obs->GetBinContent(bin));
            }
            double nll = 0.0;
            if (run.profile_minimizer == "minuit" || run.profile_minimizer == "pydme") {
              nll = profile_pl->MinimizeOverScaleMinuit(S_for_pl, profile_param_lo, profile_param_hi).second;
            } else {
              nll = profile_pl->MinimizeOverScale(S_for_pl, profile_param_lo, profile_param_hi).second;
            }
            nll_values.push_back(nll);
            if (idx_mchi == 0 && idx_sigma == 0 && run.verbosity >= 1)
              std::cout << "[scan-pattern] Per-bin S_obs (n_e) for first grid point:\n";
            if (idx_mchi == 0 && idx_sigma == 0 && run.verbosity >= 1)
              for (size_t i = 0; i < summary.roi_bins.size(); ++i)
                std::cout << "  ne=" << summary.roi_bins[i] << "  S_obs=" << S_for_pl[i] << "\n";
          } else {
            if (!data_for_q_grid.empty() && data_for_q_grid.size() >= summary.roi_bins.size()) {
              for (size_t i = 0; i < summary.roi_bins.size(); ++i) {
                int ne = summary.roi_bins[i];
                int bin_s = S_obs->FindBin(static_cast<double>(ne));
                int bin_b = B_tot->FindBin(static_cast<double>(ne));
                data.push_back(data_for_q_grid[i]);
                model_null.push_back(B_tot->GetBinContent(bin_b));
                model_test.push_back(B_tot->GetBinContent(bin_b) + S_obs->GetBinContent(bin_s));
              }
            } else {
              std::cout << "[scan-pattern] Per-bin inputs to PLR (ROI bins):\n";
              for (int ne : summary.roi_bins) {
                int bin = S_obs->FindBin(ne);
                double s = S_obs->GetBinContent(bin);
                double b = B_tot->GetBinContent(bin);
                data.push_back(b);
                model_null.push_back(b);
                model_test.push_back(b + s);
                double q_bin = (b > 0.0 && s > 0.0) ? 2.0 * (s - b * std::log(1.0 + s / b))
                    : (b <= 0.0 && s > 0.0) ? 2.0 * s : 0.0;
                std::cout << "  ne=" << ne << "  S=" << s << "  B=" << b
                          << "  q_bin(closed-form)=" << q_bin << "\n";
              }
            }
            q_ts = ts->EvaluateRatio(data, model_test, model_null);
          }
        }

        if (!profile_pl)
          std::cout << "[scan-pattern] mchi=" << mchi << " MeV, sigma="
                    << sigma_val << " cm^2 → q=" << q_ts << "\n";

        if (!profile_pl)
          h_q.SetBinContent(idx_mchi + 1, idx_sigma + 1, q_ts);

        if (run.verbosity >= 2 && !profile_pl) {
          std::cout << "[scan-pattern] mchi=" << mchi
                    << " MeV, sigma=" << sigma_val
                    << " cm^2 → q=" << q_ts << "\n";
        }

        ++idx_sigma;
      }

      if (profile_pl) {
        if (nll_values.size() != sigma_list.size()) {
          if (run.verbosity >= 1)
            std::cout << "[scan-pattern] mchi=" << mchi << " MeV: nll_values.size()=" << nll_values.size()
                      << " != sigma_list.size()=" << sigma_list.size() << "; using fallback UL and skipping q_mu curve.\n";
          h_upper_limit.SetBinContent(idx_mchi + 1, sigma_list.back());
        }
      }
      if (profile_pl && !use_pattern_bins && nll_values.size() == sigma_list.size()) {
        // n_e mode: q_mu and UL from grid (no 2D minimizer)
        const double nll_min = *std::min_element(nll_values.begin(), nll_values.end());
        const double q0_val = 2.0 * (nll_null - nll_min);
        h_q0.SetBinContent(idx_mchi + 1, q0_val > 0.0 ? q0_val : 0.0);
        // Monotonicize q(σ): running max so UL crossing is well-defined and smooth
        std::vector<double> q_mu(nll_values.size()), q_mono(nll_values.size());
        for (size_t k = 0; k < nll_values.size(); ++k) {
          double q = 2.0 * (nll_values[k] - nll_min);
          q_mu[k] = (q > 0.0) ? q : 0.0;
        }
        q_mono[0] = q_mu[0];
        for (size_t k = 1; k < nll_values.size(); ++k)
          q_mono[k] = std::max(q_mono[k - 1], q_mu[k]);
        double ul_sigma = UlFromQMonoCrossing(sigma_list, q_mono, target_q);
        for (int k = 0; k < static_cast<int>(nll_values.size()); ++k) {
          if (q_mono[k] <= 0.0) continue;
          h_q.SetBinContent(idx_mchi + 1, k + 1, q_mono[k]);
        }
        h_upper_limit.SetBinContent(idx_mchi + 1, ul_sigma);
      }
      if (profile_pl && use_pattern_bins && nll_values.size() == sigma_list.size()) {
        const double nll_min_grid = *std::min_element(nll_values.begin(), nll_values.end());
        // Use 2D nll_min when pydme_style_ul and 2D succeeded (matches pydme); else grid minimum to avoid spurious flat curve.
        const bool pydme_mode = (run.profile_minimizer == "pydme");
        const double nll_min = (run.pydme_style_ul && use_2d_nll_min) ? nll_min_2d : nll_min_grid;
        if (use_2d_nll_min && nll_min_2d < nll_min_grid && run.verbosity >= 1)
          std::cout << "[scan-pattern] mchi=" << mchi << " MeV " << run.profile_minimizer
                    << ": 2D nll_min (" << nll_min_2d << ") < grid min (" << nll_min_grid
                    << "); using " << (run.pydme_style_ul ? "2D" : "grid") << " for q_mu/UL"
                    << (run.pydme_style_ul ? " (pydme_style_ul)." : " to avoid spurious curve.") << "\n";
        const double q0_val = 2.0 * (nll_null - nll_min);
        h_q0.SetBinContent(idx_mchi + 1, q0_val > 0.0 ? q0_val : 0.0);

        // Monotonicize q(σ): running max so UL crossing is well-defined and reduces sawtooth
        std::vector<double> q_mu(nll_values.size()), q_mono(nll_values.size());
        for (size_t k = 0; k < nll_values.size(); ++k) {
          double q = 2.0 * (nll_values[k] - nll_min);
          q_mu[k] = (q > 0.0) ? q : 0.0;
        }
        q_mono[0] = q_mu[0];
        for (size_t k = 1; k < nll_values.size(); ++k)
          q_mono[k] = std::max(q_mono[k - 1], q_mu[k]);

        double ul_sigma = UlFromQMonoCrossing(sigma_list, q_mono, target_q);
        double ul_pydme_bisection = -1.0;
        if (pydme_mode && S_grid.size() >= 2u) {
          // Pydme diagnostic: bracket + bisection with re-minuit at each trial σ (can be spiky on fine mχ grids).
          const double log10_lo = std::log10(sigma_list.front());
          const double log10_hi = std::log10(sigma_list.back());
          auto S_from_log10 = [&S_grid, &sigma_list, log10_lo, log10_hi](double log10_s) -> std::vector<double> {
            const size_t n = S_grid.empty() ? 0u : S_grid[0].size();
            std::vector<double> out(n, 0.0);
            if (S_grid.size() < 2u) return S_grid.empty() ? out : S_grid[0];
            const double log10_s_clamp = std::max(log10_lo, std::min(log10_hi, log10_s));
            for (size_t j = 0; j + 1 < sigma_list.size(); ++j) {
              const double l0 = std::log10(sigma_list[j]);
              const double l1 = std::log10(sigma_list[j + 1]);
              if (log10_s_clamp >= l0 && log10_s_clamp <= l1) {
                const double t = (l1 - l0) > 1e-300 ? (log10_s_clamp - l0) / (l1 - l0) : 0.0;
                for (size_t b = 0; b < n; ++b)
                  out[b] = S_grid[j][b] + t * (S_grid[j + 1][b] - S_grid[j][b]);
                return out;
              }
            }
            if (log10_s_clamp <= std::log10(sigma_list[0])) return S_grid[0];
            return S_grid.back();
          };
          auto q_mu_at = [&](double log10_sig) {
            std::vector<double> S = S_from_log10(log10_sig);
            const double nll = profile_pl->MinimizeOverScaleMinuit(S, profile_param_lo, profile_param_hi).second;
            return 2.0 * (nll - nll_min);
          };
          const int k_best_pydme = static_cast<int>(std::min_element(nll_values.begin(), nll_values.end()) - nll_values.begin());
          const double log10_sigma_best = std::log10(sigma_list[k_best_pydme]);
          const double lo = use_2d_nll_min
              ? std::max({log10_sigma_hat_pydme, log10_lo, log10_sigma_best})
              : std::max(log10_lo, log10_sigma_best);
          double hi = lo;
          const double ul_brack_step = 0.3;
          const int ul_max_expand = 12;
          const int ul_max_iter = 24;
          const double ul_q_tol = 0.01;
          const double tol_x = std::max(1e-3, 0.01 * (log10_hi - log10_lo));
          double step = ul_brack_step;
          int brack_count = 0;
          for (int _ = 0; _ < ul_max_expand && hi < log10_hi - 1e-12; ++_) {
            brack_count++;
            hi = std::min(hi + step, log10_hi);
            if (q_mu_at(hi) >= target_q) break;
            step *= 2.0;
          }
          if (q_mu_at(hi) >= target_q) {
            double left = lo, right = hi;
            for (int it = 0; it < ul_max_iter; ++it) {
              const double mid = 0.5 * (left + right);
              const double q_mid = q_mu_at(mid);
              if (q_mid >= target_q)
                right = mid;
              else
                left = mid;
              if (std::abs(right - left) < tol_x || std::abs(q_mid - target_q) < ul_q_tol)
                break;
            }
            ul_pydme_bisection = std::pow(10.0, right);
            if (run.verbosity >= 1)
              std::cout << "[scan-pattern] mchi=" << mchi << " MeV pydme bisection (diagnostic): log10(sigma_e)="
                        << std::log10(ul_pydme_bisection) << " (bracketing steps=" << brack_count << ")\n";
          } else if (run.verbosity >= 1) {
            const double q_at_hi = q_mu_at(log10_hi);
            std::cout << "[scan-pattern] mchi=" << mchi << " MeV pydme bisection: bracket did not reach target_q (q at log10_sigma_hi="
                      << log10_hi << " is " << q_at_hi << " < " << target_q << ")\n";
          }
        }
        if (ul_pydme_bisection > 0.0)
          ul_pydme_bisection_vals[static_cast<std::size_t>(idx_mchi)] = ul_pydme_bisection;
        for (int k = 0; k < static_cast<int>(nll_values.size()); ++k) {
          if (q_mono[k] <= 0.0) continue;
          h_q.SetBinContent(idx_mchi + 1, k + 1, q_mono[k]);
        }
        h_upper_limit.SetBinContent(idx_mchi + 1, ul_sigma);
        std::cout << "[scan-pattern] mchi=" << mchi << " MeV → q0=" << q0_val
                  << " upper_limit(sigma_e)=" << ul_sigma << " cm^2\n";
      }

      ++idx_mchi;
    }

    // =========================================================================
    // 11. Post-processing: build UL graph and optional pydme bisection diagnostic
    //     UL graph = q(σ) grid crossing with optional spike-smoothing envelope.
    //     Pydme bisection graph is a re-minimisation diagnostic (pydme mode only).
    // =========================================================================
    std::vector<double> ul_sigma_raw;
    TGraph g_upper_limit;
    TGraph g_pydme_bisection;
    bool have_pydme_bisection_graph = false;
    if (profile_pl) {
      const int n_mchi_lim = h_upper_limit.GetNbinsX();
      ul_sigma_raw.resize(static_cast<std::size_t>(n_mchi_lim));
      for (int i = 0; i < n_mchi_lim; ++i)
        ul_sigma_raw[static_cast<std::size_t>(i)] = h_upper_limit.GetBinContent(i + 1);

      if (run.smooth_ul_envelope) {
        std::vector<double> sigma_lim = ul_sigma_raw;
        for (int pass = 0; pass < 10; ++pass) {
          bool changed = false;
          for (int i = 1; i < n_mchi_lim - 1; ++i) {
            const double s_prev = sigma_lim[static_cast<std::size_t>(i - 1)];
            double& s_curr = sigma_lim[static_cast<std::size_t>(i)];
            const double s_next = sigma_lim[static_cast<std::size_t>(i + 1)];
            if (s_curr <= 0.0 || s_prev <= 0.0 || s_next <= 0.0) continue;
            if (s_curr > s_prev && s_curr > s_next) {
              const double cap = std::max(s_prev, s_next);
              if (s_curr > cap) {
                s_curr = cap;
                changed = true;
              }
            }
          }
          if (!changed) break;
        }
        for (int i = 0; i < n_mchi_lim; ++i)
          h_upper_limit.SetBinContent(i + 1, sigma_lim[static_cast<std::size_t>(i)]);
        if (run.verbosity >= 1)
          std::cout << "[scan-pattern] smooth_ul_envelope: applied local-maximum cap to TH1D\n";
      }

      g_upper_limit = TGraph(n_mchi_lim);
      g_upper_limit.SetName("upper_limit_sigma_e_mchi_graph");
      g_upper_limit.SetTitle(";m_{#chi} [MeV];#sigma_{e} [cm^{2}] (90% CL)");
      for (int i = 0; i < n_mchi_lim; ++i) {
        g_upper_limit.SetPoint(i, mchi_list[static_cast<std::size_t>(i)],
                               ul_sigma_raw[static_cast<std::size_t>(i)]);
      }

      std::vector<double> pydme_m, pydme_s;
      for (int i = 0; i < n_mchi_lim; ++i) {
        const double s = ul_pydme_bisection_vals[static_cast<std::size_t>(i)];
        if (s > 0.0) {
          pydme_m.push_back(mchi_list[static_cast<std::size_t>(i)]);
          pydme_s.push_back(s);
        }
      }
      if (!pydme_m.empty()) {
        have_pydme_bisection_graph = true;
        g_pydme_bisection = TGraph(static_cast<int>(pydme_m.size()));
        g_pydme_bisection.SetName("upper_limit_sigma_e_mchi_pydme_bisection");
        g_pydme_bisection.SetTitle(";m_{#chi} [MeV];#sigma_{e} [cm^{2}] (90% CL, pydme bisection diagnostic)");
        for (int i = 0; i < static_cast<int>(pydme_m.size()); ++i)
          g_pydme_bisection.SetPoint(i, pydme_m[static_cast<std::size_t>(i)], pydme_s[static_cast<std::size_t>(i)]);
      }
    }

    // =========================================================================
    // 12. Write ROOT output
    //     Writes: q_mchi_sigma_pattern, q0_mchi, upper_limit_sigma_e_mchi,
    //             upper_limit graph, B_tot_ne, validation histograms,
    //             exposure_kg_year, and optional per-point spectra dumps.
    // =========================================================================
    std::string out_path = run.outdir + "/scan_dmelectron_pattern.root";
    TFile fout(out_path.c_str(), "RECREATE");
    if (!fout.IsOpen()) {
      std::cerr << "[scan-pattern] ERROR: cannot create output file " << out_path << "\n";
      return 1;
    }

    if (run.background_source != "bp_br_template")
      B_tot->Write("B_tot_ne");
    h_q.Write("q_mchi_sigma_pattern");
    if (profile_pl) {
      h_q0.Write("q0_mchi");
      h_upper_limit.Write("upper_limit_sigma_e_mchi");
      g_upper_limit.Write("upper_limit_sigma_e_mchi_graph");
      if (have_pydme_bisection_graph)
        g_pydme_bisection.Write("upper_limit_sigma_e_mchi_pydme_bisection");
    }
    if (h_S_pat_validation) h_S_pat_validation->Write();
    if (h_B_pat_validation) h_B_pat_validation->Write();
    if (run.dump_point_spectra_root) {
      for (auto& h : dump_spectra_hists) {
        if (h) h->Write();
      }
    }
    // Always write the exposure used for this scan (config: livetime_days * duty_cycle * mass_kg / 365.25)
    {
      fout.cd();
      TParameter<double> p_exp_used("exposure_kg_year", summary.exposure_kg_year);
      p_exp_used.Write();
    }
    if (!data_for_output.empty()) {
      const int np = static_cast<int>(data_for_output.size());
      if (use_pattern_bins && np == static_cast<int>(summary.pattern_roi.size())) {
        TH1D h_D_pat("D_pat", "Observed counts per pattern (data);pattern bin;counts",
                     np, 0.5, np + 0.5);
        for (int i = 0; i < np; ++i) {
          h_D_pat.SetBinContent(i + 1, data_for_output[i]);
          h_D_pat.GetXaxis()->SetBinLabel(i + 1, std::to_string(summary.pattern_roi[i]).c_str());
        }
        h_D_pat.Write();
      } else if (!use_pattern_bins && np == static_cast<int>(summary.roi_bins.size())) {
        TH1D h_D_ne("D_ne", "Observed counts per n_e bin (data);n_e;counts",
                    np, 0.5, np + 0.5);
        for (int i = 0; i < np; ++i) {
          h_D_ne.SetBinContent(i + 1, data_for_output[i]);
          h_D_ne.GetXaxis()->SetBinLabel(i + 1, ("n_e=" + std::to_string(summary.roi_bins[i])).c_str());
        }
        h_D_ne.Write();
      }
      double data_exposure = 0.0, data_mass = 0.0;
      if (get_exposure_from_data_file(run.data_path, &data_exposure) && data_exposure > 0.0) {
        fout.cd();
        TParameter<double> p_exp_data("exposure_kg_year_from_data_file", data_exposure);
        p_exp_data.Write();
      }
      TFile fin(run.data_path.c_str(), "READ");
      if (fin.IsOpen()) {
        TParameter<double>* p_mass = nullptr;
        fin.GetObject("mass_kg", p_mass);
        if (p_mass && p_mass->GetVal() > 0.0) {
          data_mass = p_mass->GetVal();
          fin.Close();
          fout.cd();
          TParameter<double> p_m_out("mass_kg", data_mass);
          p_m_out.Write();
        } else {
          fin.Close();
        }
      }
    }
    fout.Close();

    // =========================================================================
    // 13. Optional: profile likelihood plot at a single mχ
    //     Produces a PDF of q_μ(log₁₀ σ) for the mass closest to
    //     run.profile_likelihood_plot_mchi, marking the NLL minimum and UL.
    // =========================================================================
    if (profile_pl && run.profile_likelihood_plot_mchi > 0 &&
        !mchi_list.empty() && !sigma_list.empty()) {
      int plot_idx_mchi = 0;
      double dm_min = 1e99;
      for (std::size_t i = 0; i < mchi_list.size(); ++i) {
        double d = std::abs(mchi_list[i] - run.profile_likelihood_plot_mchi);
        if (d < dm_min) {
          dm_min = d;
          plot_idx_mchi = static_cast<int>(i);
        }
      }
      const double mchi_plot = mchi_list[plot_idx_mchi];
      const int n_sig = static_cast<int>(sigma_list.size());
      std::vector<double> log_sigma(n_sig), q_mu_vals(n_sig);
      int best_k = 0;
      double q_min = 1e99;
      for (int k = 0; k < n_sig; ++k) {
        const double q = h_q.GetBinContent(plot_idx_mchi + 1, k + 1);
        log_sigma[k] = std::log10(sigma_list[k]);
        q_mu_vals[k] = q;
        if (q >= 0.0 && q < q_min) {
          q_min = q;
          best_k = k;
        }
      }
      double ul_sigma = h_upper_limit.GetBinContent(plot_idx_mchi + 1);
      if (ul_sigma <= 0.0 || !std::isfinite(std::log10(ul_sigma))) {
        ul_sigma = sigma_list.back();
        if (run.verbosity >= 1)
          std::cout << "[scan-pattern] Profile plot: upper limit bin was invalid; using sigma_list.back()=" << ul_sigma << "\n";
      }
      const double log_sigma_best = std::log10(sigma_list[best_k]);
      const double log_sigma_ul = std::log10(ul_sigma);
      const double log_sigma_lo = log_sigma.front();
      const double log_sigma_hi = log_sigma.back();
      const double q_max = *std::max_element(q_mu_vals.begin(), q_mu_vals.end());
      const double y_max = std::max(q_max, target_q) * 1.15;
      const double y_plot = y_max < 0.5 ? 1.0 : y_max;

      TCanvas c1("c1", "Profile likelihood", 800, 600);
      c1.SetGrid(true, true);
      TGraph g(n_sig, log_sigma.data(), q_mu_vals.data());
      g.SetTitle(("Profile likelihood for m_{#chi} = " + std::to_string(mchi_plot) + " MeV").c_str());
      g.GetXaxis()->SetTitle("log_{10} #bar{#sigma}_{e} [cm^{2}]");
      g.GetYaxis()->SetTitle("#tilde{q}_{#mu}");
      g.GetYaxis()->SetRangeUser(-0.1, y_plot);
      g.GetXaxis()->SetLimits(log_sigma_lo - 0.05 * (log_sigma_hi - log_sigma_lo),
                              log_sigma_hi + 0.05 * (log_sigma_hi - log_sigma_lo));
      g.SetMarkerStyle(20);
      g.SetMarkerSize(0.8);
      g.Draw("APL");

      TLine l_best(log_sigma_best, 0.0, log_sigma_best, y_plot);
      l_best.SetLineStyle(2);
      l_best.SetLineColor(kRed);
      l_best.Draw();

      TLine l_ul(log_sigma_ul, 0.0, log_sigma_ul, y_plot);
      l_ul.SetLineStyle(2);
      l_ul.SetLineColor(kBlue);
      l_ul.Draw();

      TLine l_thresh(log_sigma_lo, target_q, log_sigma_hi, target_q);
      l_thresh.SetLineStyle(2);
      l_thresh.SetLineColor(kBlue);
      l_thresh.Draw();

      const double quantile_1side = TMath::NormQuantile(run.cl);
      const int cl_pct = static_cast<int>(std::round(run.cl * 100));
      std::ostringstream ss_best, ss_ul;
      ss_best << std::fixed << std::setprecision(2) << log_sigma_best;
      ss_ul << std::fixed << std::setprecision(2) << log_sigma_ul;
      TLatex tx;
      tx.SetNDC(true);
      tx.SetTextSize(0.035);
      tx.DrawLatex(0.18, 0.82, ("nLL min #bar{#sigma}_{e} = " + ss_best.str()).c_str());
      tx.DrawLatex(0.18, 0.78, ("Upper limit: " + ss_ul.str() + " [" + std::to_string(cl_pct) + "% CL (" + std::to_string(static_cast<int>(quantile_1side * 100) / 100.0) + ")]").c_str());

      std::string pdf_path = run.outdir + "/profile_likelihood_mchi_";
      if (mchi_plot == std::floor(mchi_plot))
        pdf_path += std::to_string(static_cast<int>(mchi_plot));
      else
        pdf_path += std::to_string(static_cast<int>(mchi_plot * 10) / 10.0);
      pdf_path += ".pdf";
      c1.SaveAs(pdf_path.c_str());
      std::cout << "[scan-pattern] Profile likelihood plot written to " << pdf_path << "\n";
    }

    std::cout << "[scan-pattern] Done. Output written to " << out_path << "\n";
  }
  catch (const std::exception& ex) {
    std::cerr << "[scan-pattern] ERROR: " << ex.what() << "\n";
    return 1;
  }

  return 0;
}
